#############################################################
#  Message File: AIVase.msg                                 #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: December 04, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

{100}{}{당신은 단순한 꽃병을 본다.}
{101}{}{당신은 작은 상자를 본다.}
{102}{}{당신은 햇빛으로 구운 점토 꽃병을 본다.}
{103}{}{당신은 주술사의 약초 상자를 본다.}
{104}{}{당신은 주술사의 물건을 솜씨좋게 훔친다.}
{105}{}{당신은 능숙하게 상자를 잠근다.}
{106}{}{당신은 능숙하게 상자의 잠금을 푼다.}
