#############################################################
#  Message File: diDiary.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 13,1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

{100}{}{당신은 낡은 일기장을 보고있다.}
{101}{}{어린 소녀의 것으로 보이는 일기장이다. 안쪽 표지에는 "안나의 소유물"이라고 적혀 있다. 대부분의 페이지는 찢어지거나 빛이 바랬지만, 한 페이지는 아직 읽을 수 있다. "271일: 오늘 엄마가 금색 펜던트를 주셨다. 내가 가져본 것 중 가장 아름다운 물건이다. 절대 이것과 떨어지지 않을 거야."}
{102}{}{이 낡은 일기장은 계속 들고있기엔 너무 낡았다.}
