#############################################################
#  Message File: diStill.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 13,1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

{100}{}{당신은 증류기를 보고있다.}
{101}{}{아아, 그래 베키가 증류기를 갖고 있었군. 이 정보를 프랭키에게 알려줘야 하겠어.}
{102}{}{당신은 망가진 증류기를 보고있다.}
{103}{}{이 증류기는 파괴되어 있다.}