#############################################################
#  Message File: Klacamall.msg                              #
#                                                           #
#  Created: August 28, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{당신은 트래퍼 타운에 들어왔다.}