#############################################################
#  Message File: Klatrap.msg                                #
#                                                           #
#  Created: August 28, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{당신은 삼림 지역에 들어왔다.}