#############################################################
#  Message File: ModMain.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{작고, 옛스러운 농작 공동체가 다 죽어가는 거대한 농작물 밭에 둘러싸여 있다.}

# from the vermin hunter seed
{500}{}{내가 저 놈들을 다 죽인것 같은 걸}
{501}{}{물어대는 악당들은 모두 죽었다.}
{502}{}{당신은 패럴의 정원을 정리했다.}

# Coin Bag Descriptions
{600}{}{당신은 동전 가방을 본다.}
{601}{}{당신은 동전 가방을 본다. 아마도 누군가가 소원을 빌면서 샘에 던져 놓은 것 같다.}
{610}{}{이 동전들은 나의 꿈이며, 나의 소망이니, 내가 도로 가져 가겠어. 내가 모조리 도로 가져 갈 테야.}

# KILL THEM ALL
{1000}{}{모두 죽여라!}
{1001}{}{슬래그에게 죽음을!}
{1002}{}{놈들이 비명지르는 것을 보고 싶군!}
{1003}{}{전부 잡아 버려!}

# fall through floor
{1100}{}{당신은 어둑어둑한 동굴 속으로 약 15피트가량 떨어집니다. 벽 쪽에는 각종 농기구가 가지런히 보관되어 있습니다.}

# blown out of hole
{1200}{}{당신은 뒤에서 폭발이 일어나기 직전에 구멍에서 빠져나왔고, 폭발의 여파로 공중으로 붕 떴습니다.}
