#############################################################
#  Message File: ZClScorp.msg                               #
#                                                           #
#       Body Type:  Lesser Scorpion                         #
#       Combat AI: Scorpion AI                              #
#       Weapons:                                            #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{당신은 전갈을 본다.}
{500}{}{당신은 브라민을 위협하는 모든 방사능전갈을 죽였다.}