
#
# Messages for Maps
#

#
# Map Names for (Automap) Descriptions
#	Note: This order must *NOT* change!
#
#	Note: The maximum description width is approximately:
#	  "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#	  but it's proportional, so you need to double-check it by
#	  going into mapper/game and going to the automap for that map.
#
#	Note: Descriptions *MUST* *NOT* be empty, and so temporary
#	  descriptions are just the map name itself (this also helps
#	  pinpoint unfinished ones when you go through here).
#
{100}{}{사막}                           # DESERT1.MAP
{101}{}{사막}                           # DESERT2.MAP
{102}{}{사막}                           # DESERT3.MAP
{103}{}{아로요}                           # arcaves.MAP
{104}{}{아로요}                           # arvillag.MAP
{105}{}{아로요}                           # arbridge.MAP
{106}{}{더 덴}                          # denbus1.MAP
{107}{}{더 덴}                          # denbus2.MAP
{108}{}{더 덴}                          # denres1.MAP
{109}{}{클래머스}                          # .MAP  ;Downtown
{110}{}{클래머스}                          # .MAP  ;Mall
{111}{}{클래머스}                          # .MAP  ;Rat Caves
{112}{}{클래머스}                          # .MAP  ;Toxic Caves
{113}{}{클래머스}                          # .MAP  ;Trapping Caves
{114}{}{클래머스}                          # .MAP  ;Grazing Area
{115}{}{볼트 시티}                       # vctyctyd.MAP
{116}{}{볼트 시티}                       # vctydwtn.MAP
{117}{}{볼트 시티}                       # vctycocl.MAP
{118}{}{오류: 지도 이름}                        # .MAP
{119}{}{도시 유적}                            # CITY1.MAP
{120}{}{해안}                                 # COAST1.MAP
{121}{}{해안}                                 # COAST2.MAP
{122}{}{사막}                                # COLATRUK.MAP
{123}{}{사막}                                # FSAUSER.MAP
{124}{}{오류: 지도 이름}                              # RAIDERS.MAP
{125}{}{오류: 지도 이름}                          # SHADYE.MAP
{126}{}{오류: 지도 이름}                          # SHADYW.MAP
{127}{}{오류: 지도 이름}                                 # GLOWENT.MAP
{128}{}{오류: 지도 이름}                             # LAADYTUM.MAP
{129}{}{오류: 지도 이름}                             # LAFOLLWR.MAP
{130}{}{오류: 지도 이름}                        # MBENT.MAP
{131}{}{오류: 지도 이름}                        # MBSTRG12.MAP
{132}{}{오류: 지도 이름}                        # MBVATS12.MAP
{133}{}{오류: 지도 이름}                        # MSTRLR12.MAP
{134}{}{오류: 지도 이름}                        # MSTRLR34.MAP
{135}{}{오류: 지도 이름}                             # V13ENT.MAP
{136}{}{오류: 지도 이름}                                  # HUBENT.MAP
{137}{}{허브}                                  # DETHCLAW.MAP
{138}{}{허브}                                  # HUBDWNTN.MAP
{139}{}{허브}                                  # HUBHEIGT.MAP
{140}{}{허브}                                  # HUBOLDTN.MAP
{141}{}{허브}                                  # HUBWATER.MAP
{142}{}{글로우}                                 # GLOW1.MAP
{143}{}{글로우}                                 # GLOW2.MAP
{144}{}{본야드}                             # LABLADES.MAP
{145}{}{본야드}                             # LARIPPER.MAP
{146}{}{본야드}                             # LAGUNRUN.MAP
{147}{}{대성당}                            # CHILDEAD.MAP
{148}{}{군사 기지}                             # MBDEAD.MAP
{149}{}{산맥}                            # MOUNTN1.MAP
{150}{}{산맥}                            # MOUNTN2.MAP
{151}{}{사막}                               # FOOT.MAP
{152}{}{사막}                               # TARDIS.MAP
{153}{}{사막}                               # TALKCOW.MAP
{154}{}{사막}                               # USEDCAR.MAP
{155}{}{브라더후드}                          # BRODEAD.MAP
{156}{}{사막}                               # DESCRVN1.MAP
{157}{}{사막}                               # DESCRVN2.MAP
{158}{}{산맥}                            # MNTCRVN1.MAP
{159}{}{산맥}                            # MNTCRVN2.MAP
{160}{}{바이퍼 캠프}
{161}{}{황야}
{162}{}{산}
{163}{}{황야}
{164}{}{산}
{165}{}{EPA}                                 # epax.MAP
{166}{}{EPA}                                 # EPAMAIN.MAP
{167}{}{EPA 창고}                       # epawrhse.MAP
{168}{}{상인}                            # vilmerch.map
{169}{}{시 잠수함}                       # sfsub.map


#
# City elevation names -- AUTOMAP Names!
#
# Format: 3 (max elevations), by city
#
# 00: Desert, DESERT1.MAP
{200}{}{황야}
{201}{}{}
{202}{}{}
# 01: Desert, DESERT2.MAP
{203}{}{황야}
{204}{}{}
{205}{}{}
# 02: Desert, DESERT3.MAP
{206}{}{황야}
{207}{}{}
{208}{}{}
# 03: Arroyo Temple, ARCAVES.MAP
{209}{}{사원: 현관}
{210}{}{사원: 복도}
{211}{}{사원: 내부 성소}
# 04: Arroyo Village, .MAP
{212}{}{마을}
{213}{}{}
{214}{}{}
# 05: Arroyo Bridge, .MAP
{215}{}{다리}
{216}{}{파괴된 다리}
{217}{}{}
# 06: Den, denbus1.MAP
{218}{}{서부}
{219}{}{}
{220}{}{}
# 07: Den, denbus2.MAP
{221}{}{동부}
{222}{}{}
{223}{}{}
# 08: Den, denres1.MAP
{224}{}{거주 구역}
{225}{}{}
{226}{}{}
# 09: , .MAP ;Klamath Downtown
{227}{}{시내}
{228}{}{시내}
{229}{}{시내}
# 10: , .MAP ;Klamath Mall
{230}{}{상점가}
{231}{}{상점가}
{232}{}{}
# 11: , .MAP ;Klamath Rat Caves
{233}{}{쥐굴}
{234}{}{쥐굴}
{235}{}{쥐굴}
# 12: , .MAP ;Klamath Toxic Caves
{236}{}{입구}
{237}{}{폐 터널}
{238}{}{저장고}
# 13: , .MAP ;Klamath Trapping Caves
{239}{}{ㅤㄷㅓㅈ 사냥터}
{240}{}{ㅤㄷㅓㅈ 사냥터}
{241}{}{ㅤㄷㅓㅈ 사냥터}
# 14: , .MAP ;Klamath Grazing Area
{242}{}{방목지}
{243}{}{방목지}
{244}{}{}
# 15: , .MAP ; Vault City Courtyard
{245}{}{안뜰}
{246}{}{}
{247}{}{}
# 16: , .MAP ; Vault City Downtown
{248}{}{시내}
{249}{}{}
{250}{}{}
# 17: , .MAP ; Vault City Council
{251}{}{의회 구역}
{252}{}{}
{253}{}{}
# 18: , .MAP ; Modoc Main Street
{254}{}{중심가}
{255}{}{}
{256}{}{}
# 19: , .MAP ; Modoc Bed & Breakfast
{257}{}{민박집}
{258}{}{민박집}
{259}{}{}
# 20: , .MAP ; Modoc Brahmin Pastures
{260}{}{브라민 목초지}
{261}{}{}
{262}{}{}
# 21: , .MAP ; Modoc Farrel's Garden
{263}{}{파렐의 정원}
{264}{}{}
{265}{}{}
# 22: , .MAP ; Modoc Down the Shitter
{266}{}{화장실 아래}
{267}{}{}
{268}{}{}
# 23: , .MAP ; Modoc Town Hall
{269}{}{마을 우물}
{270}{}{}
{271}{}{}
# 24: , .MAP ; Modoc Ghost Town: The Ghost Farm
{272}{}{농장}
{273}{}{}
{274}{}{}
# 25: , .MAP ; Modoc Ghost Town: Main Cavern
{275}{}{동굴}
{276}{}{}
{277}{}{}
# 26: , .MAP ; Modoc Ghost Town: Underground Lake
{278}{}{지하 호수}
{279}{}{}
{280}{}{}
# 27: , .MAP ; Sierra Army Depot: The Battlefield
{281}{}{전장}
{282}{}{}
{283}{}{}
# 28: , .MAP ; Sierra Army Depot: Levels 1-3
{284}{}{인사부}
{285}{}{보관소}
{286}{}{로봇공학 연구소}
# 29: , .MAP ; Sierra Army Depot: Level 4
{287}{}{생체 연구 실험실}
{288}{}{}
{289}{}{}
# 30: Vault City Vault, .MAP
{290}{}{볼트: 레벨 1}
{291}{}{볼트: 레벨 2}
{292}{}{볼트: 레벨 3}
# 31: Gecko Settlement
{293}{}{정착지}
{294}{}{정착지}
{295}{}{정착지}
# 32: Gecko Power Plant, .MAP
{296}{}{발전소}
{297}{}{발전소}
{298}{}{}
# 33: Gecko Junkyard, .MAP
{299}{}{폐품 처리장}
{300}{}{폐품 처리장}
{301}{}{폐품 처리장}
# 34: Gecko Access Tunnels, .MAP
{302}{}{진입로}
{303}{}{진입로}
{304}{}{진입로}
# 35: Arroyo Wilderness, .MAP
{305}{}{삼림}
{306}{}{}
{307}{}{}
# 36: Vault 15, .MAP
{308}{}{볼트 15: 레벨 1}
{309}{}{볼트 15: 레벨 2}
{310}{}{볼트 15: 레벨 3}
# 37: Vault 15, .MAP
{311}{}{무단 점유지}
{312}{}{무단 점거자들}
{313}{}{}
# 38: Vault 15, .MAP
{314}{}{무단 점유지}
{315}{}{}
{316}{}{}
# 39: Vault 15, .MAP
{317}{}{동쪽 입구}
{318}{}{}
{319}{}{}
# 40: Vault 13, .MAP
{320}{}{레벨 1}
{321}{}{레벨 2}
{322}{}{레벨 3}
# 41: Vault 13, .MAP
{323}{}{동굴}
{324}{}{}
{325}{}{}
# 42: NCR, .MAP
{326}{}{시내}
{327}{}{}
{328}{}{}
# 43: NCR, .MAP
{329}{}{의회 회관}
{330}{}{}
{331}{}{}
# 44: NCR, .MAP
{332}{}{웨스틴 목장}
{333}{}{}
{334}{}{}
# 45: NCR, .MAP
{335}{}{방목장}
{336}{}{}
{337}{}{}
# 46: NCR, .MAP
{338}{}{상점가}
{339}{}{}
{340}{}{}
# 47: NCR, .MAP
{341}{}{의회 회관}
{342}{}{}
{343}{}{}
# 48: Klamath, klacanyn.MAP
{344}{}{협곡}
{345}{}{협곡}
{346}{}{협곡}
# 49: Military Base, mbase12.MAP
{347}{}{레벨 1}
{348}{}{레벨 2}
{349}{}{}
# 50: Military Base, mbase34.MAP
{350}{}{레벨 3}
{351}{}{레벨 4}
{352}{}{}
# 51: Military Base, mbclose.MAP
{353}{}{입구}
{354}{}{}
{355}{}{}
# 52: Den Slave Run dnslvrun.MAP
{356}{}{황야}
{357}{}{마을}
{358}{}{야영지}
# 53: Car Desert out-of-gas, CarDesrt.MAP
{359}{}{황야}
{360}{}{}
{361}{}{}
# 54: New Reno 1 newr1.MAP
{362}{}{버진가}
{363}{}{데스페라도 지하층}
{364}{}{데스페라도 2층}
# 55: New Reno 2 newr2.MAP
{365}{}{2번가}
{366}{}{샤크 클럽 2층}
{367}{}{샤크 클럽 3층}
# 56: New Reno 3 newr3.MAP
{368}{}{상점가}
{369}{}{뉴 레노 무기상 지하층}
{370}{}{}
# 57: New Reno 4 newr4.MAP
{371}{}{동부}
{372}{}{기차역}
{373}{}{}
# 58: New Reno Chop Shop newrcs.MAP
{374}{}{불법 카센터}
{375}{}{}
{376}{}{}
# 59: New Reno GO newrgo.MAP
{377}{}{묘지}
{378}{}{방사능 낙진 대피소}
{379}{}{}
# 60: New Reno ST newrst.MAP
{380}{}{노예 우리}
{381}{}{연구소}
{382}{}{}
# 61: New Reno Boxing Arena newrba.MAP
{383}{}{권투 경기장}
{384}{}{권투 경기장}
{385}{}{권투 경기장}
# 62: Redding Wanamingo Mine Entrance  RedWame.Map
{386}{}{광산 입구}
{387}{}{광산 입구}
{388}{}{광산 입구}
# 63: Great Wanamingo Mine, Level 1 and 2  RedWan1.MAP
{389}{}{광산 1층}
{390}{}{광산 2층}
{391}{}{}
# 64: Redding Downtown  RedDown.MAP
{392}{}{시내}
{393}{}{시내}
{394}{}{시내}
# 65: Redding Mine Entrance   RedMEnt.MAP
{395}{}{광산 야영지}
{396}{}{광산 야영지}
{397}{}{광산 야영지}
# 66: Redding Downtown Tunnels  RedDTun.MAP
{398}{}{통로}
{399}{}{통로}
{400}{}{통로}
# 67: Redding Mine Entrance Tunnels
{401}{}{통로}
{402}{}{통로}
{403}{}{통로}
# 68: Random Encounter City 1
{404}{}{도시}
{405}{}{도시}
{406}{}{도시}
# 69: Random Encounter Cavern 0
{407}{}{산지}
{408}{}{산지}
{409}{}{산지}
# 70: Random Encounter Cavern 1
{410}{}{동굴}
{411}{}{동굴}
{412}{}{동굴}
# 71: Random Encounter Cavern 2
{413}{}{동굴}
{414}{}{동굴}
{415}{}{동굴}
# 72: Random Encounter Cavern 3
{416}{}{동굴}
{417}{}{동굴}
{418}{}{동굴}
# 73: Random Encounter Cavern 4
{419}{}{동굴}
{420}{}{동굴}
{421}{}{동굴}
# 74: Random Encounter Mountain 1
{422}{}{산지}
{423}{}{산지}
{424}{}{산지}
# 75: Random Encounter Mountain 2
{425}{}{산지}
{426}{}{산지}
{427}{}{산지}
# 76: Random Encounter Coast 1
{428}{}{해안}
{429}{}{해안}
{430}{}{해안}
# 77: Random Encounter Coast 2
{431}{}{해안}
{432}{}{해안}
{433}{}{해안}
# 78: Broken Hills 1  broken1.map
{434}{}{시내}
{435}{}{지하층}
{436}{}{Unused}
# 79: Broken Hills 2 broken2.map
{437}{}{거주구역}
{438}{}{지하}
{439}{}{광산}
# 80: Random Encounter Cavern 5
{440}{}{동굴}
{441}{}{동굴}
{442}{}{동굴}
# 81: Random Encounter Desert 4
{443}{}{황야}
{444}{}{황야}
{445}{}{황야}
# 82. Random Encounter Desert 5
{446}{}{황야}
{447}{}{황야}
{448}{}{황야}
# 83. Random Encounter Desert 6
{449}{}{황야}
{450}{}{황야}
{451}{}{황야}
# 84. Random Encounter Desert 7
{452}{}{황야}
{453}{}{황야}
{454}{}{황야}
# 85. Random Encounter Coast 3
{455}{}{해안}
{456}{}{해안}
{457}{}{해안}
# 86. Random Encounter Coast 4
{458}{}{해안}
{459}{}{해안}
{460}{}{해안}
# 87. Random Encounter Coast 5
{461}{}{해안}
{462}{}{해안}
{463}{}{해안}
# 88. Random Encounter Coast 6
{464}{}{해안}
{465}{}{해안}
{466}{}{해안}
# 89. Random Encounter Coast 7
{467}{}{해안}
{468}{}{해안}
{469}{}{해안}
# 90. Random Encounter Coast 8
{470}{}{해안}
{471}{}{해안}
{472}{}{해안}
# 91. Random Encounter Coast 9
{473}{}{해안}
{474}{}{해안}
{475}{}{해안}
# 92. Raiders Camp 1
{476}{}{레이더 야영지}
{477}{}{레이더 야영지}
{478}{}{레이더 야영지}
# 93. Raider Camp 2
{479}{}{동굴 입구}
{480}{}{전갈 둥지}
{481}{}{막사}
# 94. Broken Hills Random Encounter Desert
{482}{}{황야}
{483}{}{황야}
{484}{}{황야}
# 95. Broken Hills Random Encounter Mountain
{485}{}{산지}
{486}{}{산지}
{487}{}{산지}
# 96. Special Encounter: Whale
{488}{}{황야}
{489}{}{황야}
{490}{}{황야}
# 97. Special Encounter: Tin Woodsman
{491}{}{황야}
{492}{}{황야}
{493}{}{황야}
# 98. Special Encounter: Talking Head
{494}{}{황야}
{495}{}{황야}
{496}{}{황야}
# 99. Special Encounter: Federation Shuttle
{497}{}{황야}
{498}{}{황야}
{499}{}{황야}
# 100. Special Encounter: Unwashed Villagers
{500}{}{황야}
{501}{}{황야}
{502}{}{황야}
# 101. Special Encounter: Bridge
{503}{}{죽음의 다리}
{504}{}{죽음의 다리}
{505}{}{죽음의 다리}
# 102. Special Encounter: Cafe of Broken Dreams
{506}{}{깨어진 꿈들의 카페}
{507}{}{깨어진 꿈들의 카페}
{508}{}{깨어진 꿈들의 카페}
# 103. Special Encounter: Holy Hand Grenade 1
{509}{}{황야}
{510}{}{황야}
{511}{}{황야}
# 104. Special Encounter: Holy Hand Grenade 2
{512}{}{산지}
{513}{}{동굴}
{514}{}{동굴}
# 105. Special Encounter: Guardian of Forever
{515}{}{수호자}
{516}{}{볼트 13}
{517}{}{볼트 13}
# 106. Special Encounter: Toxic Waste Dump
{518}{}{유독성 폐기물 하치장}
{519}{}{유독성 폐기물 하치장}
{520}{}{유독성 폐기물 하치장}
# 107. Special Encounter: Pahiahs
{521}{}{황야}
{522}{}{황야}
{523}{}{황야}
# 108. Special Encounter: Mad Brahmin
{524}{}{황야}
{525}{}{황야}
{526}{}{황야}
# 109. Navarro Entrance
{527}{}{주유소}
{528}{}{지하}
{529}{}{버티버드 기지}
# 110. Coast Encounter 10
{530}{}{해안선}
{531}{}{해안선}
{532}{}{해안선}
# 111. Coast Encounter 11
{533}{}{해안선}
{534}{}{해안선}
{535}{}{해안선}
# 112. Coast Encounter 12
{536}{}{해안선}
{537}{}{해안선}
{538}{}{해안선}
# 113. Desert Encounter 8
{539}{}{황야}
{540}{}{황야}
{541}{}{황야}
# 114. Desert Encounter 9
{542}{}{황야}
{543}{}{황야}
{544}{}{황야}
# 115. Desert Encounter 10
{545}{}{황야}
{546}{}{황야}
{547}{}{황야}
# 116. Desert Encounter 11
{548}{}{황야}
{549}{}{황야}
{550}{}{황야}
# 117. Desert Encounter 12
{551}{}{황야}
{552}{}{황야}
{553}{}{황야}
# 118. Cavern Encounter 5
{554}{}{동굴}
{555}{}{동굴}
{556}{}{동굴}
# 119. Cavern Encounter 6
{557}{}{동굴}
{558}{}{동굴}
{559}{}{동굴}
# 120. Cavern Encounter 7
{560}{}{동굴}
{561}{}{동굴}
{562}{}{동굴}
# 121. Mountain Encounter 3
{563}{}{산지}
{564}{}{산지}
{565}{}{산지}
# 122. Mountain Encounter 4
{566}{}{산지}
{567}{}{산지}
{568}{}{산지}
# 123. Mountain Encounter 5
{569}{}{산지}
{570}{}{산지}
{571}{}{산지}
# 124. Mountain Encounter 6
{572}{}{산지}
{573}{}{산지}
{574}{}{산지}
# 125. City Encounter
{575}{}{폐허 도시}
{576}{}{폐허 도시}
{577}{}{폐허 도시}
# 126. Arroyo Temple
{578}{}{사원 입구}
{579}{}{사원 입구}
{580}{}{사원 입구}
# 127. Destroyed Arroyo
{581}{}{파괴된 다리}
{582}{}{파괴된 다리}
{583}{}{파괴된 다리}
# [Map 128] lookup_name=Enclave Detention
{584}{}{유치장}
{585}{}{유치장}
{586}{}{유치장}
# [Map 129] lookup_name=Enclave Dock
{587}{}{Dock}
{588}{}{버티버드 착륙장}
{589}{}{Dock}
# [Map 130] lookup_name=Enclave End Fight
{590}{}{현관}
{591}{}{현관}
{592}{}{현관}
# [Map 131] lookup_name=Enclave Guard Barracks
{593}{}{경비 막사}
{594}{}{경비 막사}
{595}{}{경비 막사}
# [Map 132] lookup_name=Enclave Presidential
{596}{}{대통령 구역}
{597}{}{대통령 구역}
{598}{}{대통령 구역}
# [Map 133] lookup_name=Enclave Reactor
{599}{}{원자로}
{600}{}{원자로}
{601}{}{원자로}
# [Map 134] lookup_name=Enclave Trap Room
{602}{}{복도}
{603}{}{복도}
{604}{}{복도}
# [Map 135] lookup_name=San Fran Tanker
{605}{}{유조선}
{606}{}{유조선}
{607}{}{유조선}
# [Map 136] lookup_name=San Fran Dock
{608}{}{항만}
{609}{}{항만}
{610}{}{항만}
# [Map 137] lookup_name=San Fran China
{611}{}{차이나 타운}
{612}{}{차이나 타운}
{613}{}{차이나 타운}
# 138. Shuttle Exterior
{614}{}{우주선 선착장}
{615}{}{우주선 선착장}
{616}{}{우주선 선착장}
# 139. Shuttle Interior
{617}{}{왕복선 내부}
{618}{}{왕복선 내부}
{619}{}{왕복선 내부}
# 140. Hubologist Base
{620}{}{허볼로지스트 기지}
{621}{}{허볼로지스트 기지}
{622}{}{허볼로지스트 기지}
# 141. City Encounter 3
{623}{}{파괴된 도시}
{624}{}{파괴된 도시}
{625}{}{파괴된 도시}
# 142. City Encounter 4
{626}{}{파괴된 도시}
{627}{}{파괴된 도시}
{628}{}{파괴된 도시}
# 143. City Encounter 5
{629}{}{파괴된 도시}
{630}{}{파괴된 도시}
{631}{}{파괴된 도시}
# 144. City Encounter 6
{632}{}{파괴된 도시}
{633}{}{파괴된 도시}
{634}{}{파괴된 도시}
# 145. City Encounter 7
{635}{}{파괴된 도시}
{636}{}{파괴된 도시}
{637}{}{파괴된 도시}
# 146. City Encounter 8
{638}{}{파괴된 도시}
{639}{}{파괴된 도시}
{640}{}{파괴된 도시}
# 147. New Reno VB  newrvb.MAP
{641}{}{버티버드 구역}
{642}{}{버티버드 구역}
{643}{}{버티버드 구역}
# 148. Shi Temple
{644}{}{「시」 사원}
{645}{}{}
{646}{}{형제단 기지}
# 149. In Game Movie
{647}{}{황야}
{648}{}{황야}
{649}{}{황야}
# 150. RndBess
{650}{}{황야}
{651}{}{황야}
{652}{}{황야}
# 151. Abbey Entrance
{653}{}{입구}
{654}{}{2층}
{655}{}{3층}
# 152. Abbey Basement
{656}{}{지하층}
{657}{}{이름 입력}
{658}{}{이름 입력}
# 153. Abbey Cave
{659}{}{동굴}
{660}{}{이름 입력}
{661}{}{이름 입력}
# 154. Village
{662}{}{마을}
{663}{}{마을}
{664}{}{마을}
# 155. Village
{665}{}{Woodland}
{666}{}{부족}
{667}{}{부족}
# 156. Village Waterside
{668}{}{낚시터}
{669}{}{작은 동굴}
{670}{}{이름 입력}
# 157. EPA, epax.map
{671}{}{입구}
{672}{}{환기, 수도, 발전 시설 레벨}
{673}{}{로봇 정비소}
# 158. EPA Sub-levels, EPAMAIN.map
{674}{}{레벨 1}
{675}{}{레벨 2}
{676}{}{레벨 3}
# 159. Warehouse, epawrhse.map
{677}{}{비밀 레벨}
{678}{}{이름 입력}
{679}{}{이름 입력}
# 160. Slaver Camp
{680}{}{막사}
{681}{}{이름 입력}
{682}{}{이름 입력}
# 161. Gecko Enclave Patrol
{683}{}{황야}
{684}{}{황야}
{685}{}{황야}
# 162. Hubologist Stash
{686}{}{입구}
{687}{}{레벨 1}
{688}{}{레벨 2}
# 163. Ranger Safe House 1
{689}{}{레인저 안전가옥}
{690}{}{레인저 안전가옥}
{691}{}{레인저 안전가옥}
# 164. Ranger Safe House 1
{692}{}{레인저 안전가옥}
{693}{}{레인저 안전가옥}
{694}{}{레인저 안전가옥}
# 165. Ranger Safe House 1
{695}{}{레인저 안전가옥}
{696}{}{레인저 안전가옥}
{697}{}{레인저 안전가옥}
# 166. Easter Egg Encounter
{698}{}{황야}
{699}{}{황야}
{700}{}{황야}
# 167. Merchant
{701}{}{황야}
{702}{}{황야}
{703}{}{황야}
# 168. Vault Village Merchant
{704}{}{황야}
{705}{}{황야}
{706}{}{황야}
# 169. Shi Submarine
{707}{}{잠수함 외관}
{708}{}{잠수함 내부 레벨 1}
{709}{}{}
# 170. EPA Sub-levels, EPAMAIN1.map
{710}{}{레벨 1}
{711}{}{레벨 2}
{712}{}{레벨 3}
# 171. EPA Sub-levels, EPAMAIN2.map
{713}{}{레벨 1}
{714}{}{레벨 2}
{715}{}{레벨 3}
# 172. Dr. Sheng Hideout sfsheng
{716}{}{폐가}
{717}{}{동굴}
{718}{}{}


#
#	Short City names
#
{1500}{}{아로요}
{1501}{}{덴}
{1502}{}{클라마스}
{1503}{}{모독}
{1504}{}{볼트 시티}
{1505}{}{ㅤㄱㅔㄱ코}
{1506}{}{브로큰 힐스}
{1507}{}{뉴 레노}
{1508}{}{시에라 육군 보급창}
{1509}{}{볼트 15}
{1510}{}{뉴 캘리포니아 공화국}
{1511}{}{볼트 13}
{1512}{}{군사 기지}
{1513}{}{레딩}
{1514}{}{샌 프란시스코}
{1515}{}{나바로}
{1516}{}{엔클레이브}
{1517}{}{수도원}         # Abbey
{1518}{}{움브라 부족}   # Primitive Tribe
{1519}{}{EPA}           # EPA
{1520}{}{유령 농장}
{1521}{}{연료가 떨어진 자동차}
{1522}{}{아로요}
{1523}{}{유독성 동굴}
{1524}{}{덴 노예 사냥}
{1525}{}{레이더}
{1526}{}{황야}
{1527}{}{산}
{1528}{}{파괴된 도시}
{1529}{}{해안}
{1530}{}{골고다}
{1531}{}{박살난 고래}
{1532}{}{양철 나무꾼}
{1533}{}{말하는 머리}
{1534}{}{연방 왕복선}
{1535}{}{언워시드 빌리저}
{1536}{}{다리}
{1537}{}{깨진 꿈의 카페}
{1538}{}{성기사들}
{1539}{}{보팔 쥐 동굴}
{1540}{}{영원의 수호자}
{1541}{}{유독성 폐기물 더미}
{1542}{}{들개}
{1543}{}{정신나간 브라민}
{1544}{}{상단}
{1545}{}{볼트 13}
{1546}{}{가짜 볼트 13}
{1547}{}{랜덤 인카운터}
{1548}{}{마구간}
{1549}{}{마을}
{1550}{}{노예상 야영지}
{1551}{}{허볼로지스트 은닉처}
{1552}{}{안전 가옥}
{1553}{}{안전 가옥}
{1554}{}{안전 가옥}
{1555}{}{RP 이스터 에그 인카운터}
{1556}{}{상인}
{1557}{}{상인}
{1558}{}{「시」 잠수함}
{1559}{}{버려진 집}
{1560}{}{ㅤㄱㅔㄱ코 엔클레이브 순찰대}