#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the name which will  #
#           be displayed for critter or items when they     #
#           get hit. Each script from scripts.lst should    #
#           have a name associated with it.                 #
#                                                           #
#  Created: October 06, 1997                                #
#############################################################

{101}{}{}                               # obj_dude.int    ; Player script.
{102}{}{스크립트 테스트 0}                  # Test0.int       ; Used to Test Scripts
{103}{}{스크립트 테스트 1}                  # Test1.int       ; Used to Test Scripts
{104}{}{스크립트 테스트 2}                  # Test2.int       ; Used to Test Scripts
{105}{}{스크립트 테스트 3}                  # Test3.int       ; Used to Test Scripts
{106}{}{스크립트 테스트 4}                  # Test4.int       ; Used to Test Scripts
{107}{}{스크립트 테스트 5}                  # Test5.int       ; Used to Test Scripts
{108}{}{아로요 전사}                 # ACWarior.int    ; Generic Warrior in Arroyo
{109}{}{아로요 주민}                # ACVillgr.int    ; Generic Villager of Arroyo
{110}{}{미녹}                          # ACMynoc.int     ; Mynoc, Bridge Guard of Arroyo
{111}{}{아로요 장로}                   # AHElder.int     ; Elder of Arroyo
{112}{}{하쿠닌}                        # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{문}                           # Door.int        ; generic locked and trapped door
{114}{}{일반}                        # Generic.int     ; Generic dialog for scripts
{115}{}{상자}                          # AILkBox.int     ; Locked box in Arroyo Elder's room
{116}{}{Lockbox}                        # Containr.int    ; Generic locked and trapped container
{117}{}{브라민}                        # ACBrahmn.int    ; Brahmin for pen in Arroyo
{118}{}{포자 식물}                    # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                               # ZClRat.int      ; Generic lesser rat
{120}{}{왜소한 전갈}                # ZClScorp.int    ; Generic lesser scorpion
{121}{}{왜소한 사마귀}                  # ZClManti.int    ; Generic lesser mantis
{122}{}{왜소한 데스클로}               # ZClDthCL.int    ; Generic lesser deathclaw
{123}{}{Vase}                           # AIVase.int      ; Vase in Arroyo Villager's Hut
{124}{}{상자}                          # AIChest.int     ; Chest in Arroyo Shaman's Hut
{125}{}{아로요 동굴}                   # ArCaves.int     ; Map Script for Arroyo Caves
{126}{}{나무 문}                    # DoorL100.int    ; Generic Locked Door (+100%) (Wood)
{127}{}{아로요 마을}                 # ArVillag.int    ; Map Script for Arroyo Village
{128}{}{아로요 다리}                  # ArBridge.int    ; Map Script for Arroyo Bridge
{129}{}{낡은 문}                       # AICavDor.int    ; Locked wooden door in Arroyo Caves (0/-20)
{130}{}{바닥 판}                    # SprTrp0.int     ; Generic spear Trap (0)
{131}{}{바닥 판}                    # SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{132}{}{바닥 판}                    # SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{133}{}{바닥 판}                    # SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{134}{}{바닥 판}                    # SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{135}{}{문}                           # AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{136}{}{중독자}                         # DCAddict.int    ; Addict from the Den
{137}{}{경비}                          # DCG2Grd.int     ; Gang 2 Guard from the Den
{138}{}{마을사람}                    # DCCustmr.int    ; Generic Customer in the Den
{139}{}{폭력배}                           # DCCustmr.int    ; Thug in the Den
{140}{}{고아}                         # DCOrphan.int    ; Thieving Orphan in the Den
{141}{}{조이}                           # DCJoey.int      ; Special thug in the Den
{142}{}{플릭}                          # DCFlick.int     ; Kwik N Save store owner in the Den
{143}{}{경비}                          # DCG2Grd.int     ; Gang 2 Guard in the Den
{144}{}{피티}                          # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{스미티}                         # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{메츠거}                        # dcMetzge.int    ; Metzger the Slaver in the Den
{147}{}{노예상인}                         # DCSlaver.int    ; Regular Slaver in the Den
{148}{}{터비}                          # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{안나}                           # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{빅}                            # DCVic.int       ; Trader Vic in the Den, can be a party member
{151}{}{프랭키}                        # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{레베카}                        # DCRebecc.int    ; Rebecca in the Den
{153}{}{빌리}                          # DCBilly.int     ; One-tooth Billy in the Hole in the Den
{154}{}{쉴라}                         # DCSheila.int    ; Sheila, the prostitute in the Hole in the Den
{155}{}{엄마}                            # DCMom.int       ; Mom, who run's Mom's in the Den
{156}{}{주민}                       # DCSlvRun.int    ; Generic People for Slave Runs
{157}{}{노예 사냥}                      # DNSlvRun.int    ; Map Script for Den Slave Runs
{158}{}{노예 수레}                     # DISlvCrt.int    ; Slave Cart to take the Player to Den
{159}{}{덴 상업지구}              # DenBus1.int     ; Map Script for Den business area 1
{160}{}{덴 상업지구}              # DenBus2.int     ; Map Script for Den business area 2
{161}{}{덴 거주지구}           # DenRes1.int     ; Map Script for Den residential area
{162}{}{무덤}                          # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{무덤}                          # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{무덤}                          # diMomGrv.int    ; Grave of Anna the ghost's Mom in the Den
{165}{}{유골}                          # diBones.int     ; Bones of Anna the ghost in the Den
{166}{}{일기}                          # diDiary.int     ; Diary of Anna the ghost in the Den
{167}{}{로켓}                         # diLocket.int    ; Locket of Anna the ghost in the Den
{168}{}{증류기}                          # diStill.int     ; Still that Maggie has in the basement in the Den
{169}{}{무덤}                          # ziGenGrv.int    ; Generic grave
{170}{}{블랙 잭}                     # ziBlkJck.int    ; Generic black jack table
{171}{}{노예}                          # zcSlave.int     ; Generic slave
{172}{}{블랙 잭}                     # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{문}                           # diChcDor.int    ; Church door from the Den
{174}{}{위스키 밥}                    # KCBob.int       ; Whiskey Bob from Klamath
{175}{}{크랩스}                          # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{알도}                           # KCAldo.int      ; Aldo from Klamath
{177}{}{아르딘}                          # KCArdin.int     ; Ardin from Klamath
{178}{}{아이}                          # KChild.int      ; Child from Klamath
{179}{}{시민}                        # KCitizen.int    ; Citizen from Klamath
{180}{}{메이다}                          # KCMaida.int     ; Maida from Klamath
{181}{}{사잭}                          # KCSajag.int     ; Sajag from Klamath
{182}{}{샐리}                          # KCSally.int     ; Sally from Klamath
{183}{}{스마일리}                         # KCSmiley.int    ; Smiley from Klamath
{184}{}{제니}                          # KCJenny.int     ; Jenny from Klamath
{185}{}{슬림}                           # KCSlim.int      ; Slim from Klamath
{186}{}{토르}                           # KCTorr.int      ; Torr from Klamath
{187}{}{던턴}                         # KCDunton.int    ; Dunton from Klamath
{188}{}{시민}                        # VCCrtCit.int    ; Vault City Courtyard Citizen
{189}{}{여행자}                       # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{볼트 시티 경비}               # VCCrtGrd.int    ; Vault City Courtyard Guard
{191}{}{볼트 시티 경비}               # VCInGrd.int     ; Vault City Inner Guard
{192}{}{스티브}                          # VCSteve.int     ; Steve from Vault City
{193}{}{앤드류}                         # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{볼트 시티 경비}               # VCGatGrd.int    ; Vault City Main Gate Guard
{195}{}{트로이 박사}                       # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{누렁 개}                     # KCYellow.int    ; Yellow Dog in Klamath
{197}{}{밸저스}                        # mcBaltha.int    ; Balthas in Modoc
{198}{}{코넬리우스}                      # mcCornel.int    ; Cornelius in Modoc
{199}{}{데이빈}                          # mcDavin.int     ; Davin in Modoc
{200}{}{파렐}                         # mcFarrel.int    ; Farrel in Modoc
{201}{}{그리샴}                        # mcGrisha.int    ; Grisham in Modoc
{202}{}{조}                             # mcJo.int        ; Jo in Modoc
{203}{}{조니}                          # mcJonny.int     ; Jonny in Modoc
{204}{}{칼}                           # mcKarl.int      ; Karl in Modoc
{205}{}{래디}                         # mcLaddie.int    ; Laddie in Modoc
{206}{}{미리아}                          # mcMiria.int     ; Miria in Modoc
{207}{}{보호자}                      # mcProtec.int    ; Protector in Modoc
{208}{}{로즈}                           # mcRose.int      ; Rose in Modoc
{209}{}{베거}                         # mcVegeir.int    ; Vegeir in Modoc
{210}{}{에드}                             # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{해리}                          # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{스미스 부인}                     # VCFSmith.int    ; Mrs. Smith from Vault City (Farmer)
{213}{}{멜린다}                        # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{사냥꾼}                        # KCTrapr.int     ; Generic trapper in Klamath
{215}{}{스미스 씨}                      # VCMSmith.int    ; Mr. Smith from Vault City (Farmer)
{216}{}{스키브}                         # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{그레고리 총독}              # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{간호사 필리스}                  # VCNancy.int     ; Nurse Phyllis in Vault City
{219}{}{랜달}                         # VCRandal.int    ; Chief Admenities Officer of Vault City
{220}{}{끈적거리는 물질}                            # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{바커스}                         # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{주민}                       # VCGenVil.int    ; Generic Villager around Vault City
{223}{}{스타크}                          # VCStark.int     ; Vault City Sargent Stark
{224}{}{볼트 입구 경비}               # VCVltGrd.int    ; Guard for entrance into the Vault of VC
{225}{}{조 영감}                        # VCOldJoe.int    ; Crazy Old Joe (Vault City)
{226}{}{코너}                         # VCConnar.int    ; Connar from Vault City
{227}{}{월리스}                        # VCWalace.int    ; Wallace the Customs Official (Vault City)
{228}{}{리네트}                        # VCLynett.int    ; First Citizen Lynette of Vault City
{229}{}{맥클루어}                        # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{변이된 쥐}                    # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{페스투스}                         # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{고든}                         # GCGordon.int    ; Ghoul with economic data in Gecko
{233}{}{행크}                           # GCHank.int      ; Ghoul that monitors the reactor in Gecko
{234}{}{제레미}                         # GCJerem.int     ; Ghoul in charge of supply cabinet in Gecko
{235}{}{럼피}                          # GCLumpy.int     ; Watches the Brahmin and helps Skeeter
{236}{}{스키터}                        # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{조막}                          # GCZomak.int     ; Muscle man for the Brain
{238}{}{우즈}                           # GCWooz.int      ; Bar owner and Tragic player
{239}{}{레니}                          # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{구울 경비}                    # GGCRDesk.int    ; Reactor Desk guard
{241}{}{구울 인부}                   # GCRWorkr.int    ; Reactor worker
{242}{}{발광 인부}                 # GCRGlow.int     ; Reactor glowing one
{243}{}{구울 경비}                    # GCRGuard.int    ; Reactor guard
{244}{}{로봇}                          # GCRRobot.int    ; Reactor robot
{245}{}{구울 시민}                  # GCFolk.int      ; Townsfolk in Gecko
{246}{}{맵 스크립트}                     # DepoLv1.int     ; Map script for Sierra Army Depot, Level 1
{247}{}{맵 스크립트}                     # DepoLvA.int     ; Map script for Sierra Army Depot Underground
{248}{}{맵 스크립트}                     # DepoLvB.int     ; Map script for Sierra. Underground B
{249}{}{보안 로봇}                 # WCSecBot.int    ; Sierra Base, Security Robot (generic)
{250}{}{수리 로봇}                   # WCRepBot.int    ; Sierra Base, Repair Robot (generic)
{251}{}{홀로디스크}                       # WIEvcDsk.int    ; Sierra Base, Evacuation Holodisk
{252}{}{홀로디스크}                       # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{홀로디스크}                       # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{단말기}                       # WSTerm1A.int    ; Security Computer, Level 1 -- Sierra Base
{255}{}{단말기}                       # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{단말기}                       # WSTerm2A.int    ; Security Computer, Level 2 -- Sierra Base
{257}{}{단말기}                       # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{단말기}                       # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{단말기}                       # WSTerm3A.int    ; Security Computer, Level 3 -- Sierra Base
{260}{}{단말기}                       # WSTerm3B.int    ; Skynet Terminal, Level 3 -- Sierra Base
{261}{}{단말기}                       # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{단말기}                       # WSTerm4A.int    ; Security Computer, Level 4 -- Sierra Base
{263}{}{단말기}                       # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{단말기}                       # WSTerm4C.int    ; BioStorage Computer, Level 4 -- Sierra Base
{265}{}{종이}                          # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{돕스 이등병}                  # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{두뇌 로봇}                      # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{승강기}                       # ZSElev01.int    ; Generic Elevator
{269}{}{승강기}                       # ZSElev02.int    ; Generic Elevator
{270}{}{Lockbox}                        # DITubBox.int    ; Tubby's box of inventory
{271}{}{Lockbox}                        # DIFlkBox.int    ; Flick's box of inventory
{272}{}{탠디}                          # SHTandi.int     ; Tandi the talking head in the NCR2 area
{273}{}{창살 함정}                     # ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{274}{}{창살 함정}                     # ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{275}{}{창살 함정}                     # ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{276}{}{창살 함정}                     # ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{277}{}{창살 함정}                     # ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{278}{}{창살 함정}                     # ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{279}{}{창살 함정}                     # ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{280}{}{창살 함정}                     # ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{281}{}{창살 함정}                     # ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{282}{}{창살 함정}                     # ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{283}{}{창살 함정}                     # ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{284}{}{창살 함정}                     # ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{285}{}{창살 함정}                     # ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{286}{}{창살 함정}                     # ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{287}{}{창살 함정}                     # ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{288}{}{창살 함정}                     # ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{289}{}{유령 동굴 1}                 # GstCav1.int     ; Modoc Ghost Cave 1
{290}{}{유령 동굴 2}                 # GstCav2.int     ; Modoc Ghost Cave 2
{291}{}{유령 농장}                     # GstFarm.int     ; Modoc Ghost Farm
{292}{}{모독 브라민 목초지}            # ModBrah.int     ; Modoc Brahmin Field
{293}{}{모독 정원}                   # ModGard.int     ; Modoc Garden
{294}{}{모독 여관}                      # ModInn.int      ; Modoc Inn
{295}{}{모독 중심지}                     # ModMain.int     ; Modoc Main
{296}{}{모독 오물}                     # ModShit.int     ; Modoc under the shitter
{297}{}{모독 우물}                       # ModWell.int     ; Modoc Well
{298}{}{NCR 구역 2}                     # ncr2.int        ; NCR area 2
{299}{}{아로요 정원}                 # ArGarden.int    ; Arroyo Gardens map script
{300}{}{게코}                          # ACGecko.int     ; generic Gecko creature
{301}{}{브룩 꽃}                    # AIBroc.int      ; Arroyo Broc Flower
{302}{}{잰더 뿌리}                    # AIXander.int    ; Arroyo Xander Root
{303}{}{브라민}                        # ZCBrahmn.int    ; Generic Brahmin
{304}{}{밸저스의 아내}                   # mcBalWif.int    ; Modoc Balthas wife
{305}{}{브라민}                        # mcBrahmn.int    ; Modoc brahmin
{306}{}{야생견}                       # mcAtkDog.int    ; Modoc Attack Dog
{307}{}{바위}                          # miDclRks.int    ; Modoc Rocks in front of the deathclaw cage
{308}{}{바위}                          # miShtRks.int    ; Modoc Rocks under the shitter
{309}{}{벽 금고}                      # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{동전 가방}                       # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{화장실}                         # miToilet.int    ; ; Modoc Toliet
{312}{}{상자}                            # miLstFnd.int    ; Modoc Lost and Found at Rose's
{313}{}{조던}                         # ACJordan.int    ; Jordan. Trains player in Melee
{314}{}{모리스 고모}                    # ACMorlis.int    ; Aunt Morlis. Has flint to give player
{315}{}{루카스}                          # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{퍼거스}                        # ACEric.int      ; Whiny person asking to fix the well
{317}{}{우물}                           # ASWell.int      ; Arroyo Well. It's broken. Fix w/ Repair
{318}{}{그루서}                        # OCGrutha.int    ; Vault 13 Gruthar Deathclaw leader
{319}{}{맵 스크립트}                     # Kladwtwn.int    ; Map script for Klamath Downtown
{320}{}{두퍼스}                         # SCSkeete.int    ; Doofus dialog script for NCR Entrance area
{321}{}{네이거}                          # ACNagor.int     ; You cousin who has lost his dog
{322}{}{스모크}                          # ACDog.int       ; Nagor's dog Smoke
{323}{}{NCR 구역 1}                     # Ncr1.int        ; Ncr area 1 map
{324}{}{NCR 구역 3}                     # Ncr3.int        ; Ncr area 3 map
{325}{}{NCR 구역 4}                     # Ncr4.int        ; Ncr area 4 map
{326}{}{NCR 구역 입구}              # Ncrent.int      ; Ncr area Entrance map
{327}{}{마이키}                          # SCMikey.int     ; NCR Lizard Dealer
{328}{}{마이키의 상자}                    # SIMbox.int      ; NCR Mikey's inventory box. (off Screen)
{329}{}{발생기}                        # WSEmit1a.int    ; Emitter, Level 1, Section A   (Sierra Base)
{330}{}{발생기}                        # WSEmit1b.int    ; Emitter, Level 1, Section B   (Sierra Base)
{331}{}{발생기}                        # WSEmit1c.int    ; Emitter, Level 1, Section C   (Sierra Base)
{332}{}{발생기}                        # WSEmit1d.int    ; Emitter, Level 1, Section D   (Sierra Base)
{333}{}{발생기}                        # WSEmit1e.int    ; Emitter, Level 1, Section E   (Sierra Base)
{334}{}{발생기}                        # WSEmit2a.int    ; Emitter, Level 2, Section A   (Sierra Base)
{335}{}{발생기}                        # WSEmit2b.int    ; Emitter, Level 2, Section B   (Sierra Base)
{336}{}{발생기}                        # WSEmit2c.int    ; Emitter, Level 2, Section C   (Sierra Base)
{337}{}{발생기}                        # WSEmit2d.int    ; Emitter, Level 2, Section D   (Sierra Base)
{338}{}{발생기}                        # WSEmit3a.int    ; Emitter, Level 3, Section A   (Sierra Base)
{339}{}{발생기}                        # WSEmit3b.int    ; Emitter, Level 3, Section B   (Sierra Base)
{340}{}{역장}                    # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{역장}                    # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{역장}                    # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{역장}                    # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{역장}                    # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{역장}                    # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{역장}                    # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{역장}                    # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{역장}                    # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{역장}                    # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{역장}                    # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{Klaxon}                         # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{버스터}                         # SCBuster.int    ; Buster gun dealer at NCR entrance
{353}{}{책장}                      # SIShelf1.int    ; Busters shelves where items are kept
{354}{}{책장}                      # SIShelf2.int    ; Busters shelves where items are kept
{355}{}{책장}                      # SIShelf3.int    ; Busters shelves where items are kept
{356}{}{레이더}                         # ECRaider.int    ; Random Encounter Raider
{357}{}{소농민}                        # ECPeasnt.int    ; Random Encounter Peasant
{358}{}{무역상}                       # ECMrchnt.int    ; Random Encounter Merchant
{359}{}{경비}                          # ECGuard.int     ; Random Encounter Guard
{360}{}{생가죽 경비}                 # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{바닥}                          # WTElFlr2.int    ; Electric Floor on Level 2 Sierra Base
{362}{}{플라즈마 함정}                    # WTPlTrp0.int    ; Plasma Trap for Sierra Base(-30)
{363}{}{플라즈마 함정}                    # WTPlTrp1.int    ; Plasma Trap for Sierra Base(-30)
{364}{}{단말기}                       # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{게시판}                 # KSBboard.int    ; Klamath bulletin board
{366}{}{입구}                           # ASCrlDr.int     ; Arroyo Corral Gate
{367}{}{끈적거리는 물질}                            # ATGoo.int       ; Goo in the Garden Map
{368}{}{문}                           # KSCVDoor.int    ; Door in Klamath Rat Caves
{369}{}{문}                           # KSMalldr.int    ; Door in Klamall..get key from Slim or Dog
{370}{}{}                               # ZCGecko.int     ; Generic gecko
{371}{}{}                               # ZCLGecko.int    ; Generic Golden Gecko
{372}{}{맵 스크립트}                     # 2ndSt.int       ; 2nd Street Map Script
{373}{}{맵 스크립트}                     # ChopShop.int    ; Chop Shop Map Script
{374}{}{맵 스크립트}                     # GeckPwpl.int    ; Gecko Power Plant Map Script
{375}{}{맵 스크립트}                     # GeckTunl.int    ; Gecko Tunnels Map Script
{376}{}{맵 스크립트}                     # KlaCnyn.int     ; Klamath Canyon Map Script
{377}{}{맵 스크립트}                     # MBase12.int     ; Military Base Level 1,2 Map Script
{378}{}{맵 스크립트}                     # MBase34.int     ; Military Base Level 3,4 Map Script
{379}{}{맵 스크립트}                     # MBClose.int     ; Military Base Closed Map Script
{380}{}{지도 스크립트}                     # ModShit.int     ; Map Script for Modoc Shitter
{381}{}{지도 스크립트}                     # NCR1.int        ; Map Script for NCR1
{382}{}{지도 스크립트}                     # NCR2.int        ; Map Script for NCR2
{383}{}{지도 스크립트}                     # NCR3.int        ; Map Script for NCR3
{384}{}{지도 스크립트}                     # NCR4.int        ; Map Script for NCR4
{385}{}{지도 스크립트}                     # NCREx.int       ; Map Script for NCR Exit
{386}{}{지도 스크립트}                     # Stable.int      ; Map Script for Stables
{387}{}{지도 스크립트}                     # V13_Orig.int    ; Map Script for Original Vault 13
{388}{}{지도 스크립트}                     # V13Ent.int      ; Map Script for Vault 13 Entrance
{389}{}{지도 스크립트}                     # V15_Orig.int    ; Map Script for Original Vault 15
{390}{}{지도 스크립트}                     # V15Ent.int      ; Map Script for Vault 15 Entrance
{391}{}{지도 스크립트}                     # Vault13.int     ; Map Script for Vault 13
{392}{}{지도 스크립트}                     # Vault15.int     ; Map Script for Vault 15
{393}{}{지도 스크립트}                     # VaultNec.int    ; Map Script for Necropolis Vault
{394}{}{지도 스크립트}                     # VCtyVlt.int     ; Map Script for Vault City Vault
{395}{}{지도 스크립트}                     # Virgin.int      ; Map Script for Virgin (these still exist?)
{396}{}{증류기}                          # Kstill.int      ; Script for still in Klamath
{397}{}{바 손님}                   # Kcggcust.int    ; Script for Klamath golden gecko customer
{398}{}{바 손님}                   # Kcbhcust.int    ; Script for Klamath buckner house customer
{399}{}{보티스}                         # SCVortis.int    ; Script for Vortis slave pen dude in NCR entrance
{400}{}{목욕 도우미}                 # Kcbgirl.int     ; Script for Klamath bath girl
{401}{}{노예}                         # SCSlaves.int    ; Script for NCR Entrance slaves
{402}{}{전갈}                       # Kcscorp.int     ; Script for Klamath scorpions on the graze map
{403}{}{브라민}                        # Kcbrahmn.int    ; Script for Klamath brahmin on the graze map
{404}{}{자동차}                            # ZSDrvCar.int    ; Drivable Car for the player
{405}{}{탁자}                          # diVicTbl.int    ; Den, table that Vic works at
{406}{}{지도 스크립트}                     # Klagraz.int     ; Map Script for Klamath graze map
{407}{}{지도 스크립트}                     # CarDesrt.int    ; Car Out of Gas Desert Map
{408}{}{지도 스크립트}                     # GeckSetl.int    ; Map Script for Gecko Settlement
{409}{}{지도 스크립트}                     # VCtyCtyd.int    ; Map Script for Vault City Courtyard
{410}{}{코르베가}                        # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{지도 스크립트}                     # KlaToxCv.int    ; Klamath Toxic Caves  Map Script
{412}{}{금속 문}                     # SISlvdor.int    ; Slave pen door in NCR Entrance
{413}{}{지도 스크립트}                     # RndDsrt.int     ; Random Encounter Desert Map Script
{414}{}{지도 스크립트}                     # RndCoast.int    ; Random Encounter Coast Map Script
{415}{}{지도 스크립트}                     # RndMnt.int      ; Random Encounter Mountain Map Script
{416}{}{Lockbox}                        # Kidbox.int      ; Klamath dunton inventory box
{417}{}{Lockbox}                        # Kibbox.int      ; Klamath buckner inventory box
{418}{}{Lockbox}                        # Kisbox.int      ; Klamath sajag inventory box
{419}{}{래치}                          # SCRatch.int     ; Ncr entrance JUNK dealer
{420}{}{권투선수}                          # ncBoxer.int     ; New Reno Generic Boxer
{421}{}{피트 맥닐리}                  # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{에반 홀리펠트}                 # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{깨무는 자}                     # ncTyson.int     ; New Reno Mike Tyson
{424}{}{과학자}                      # ncScient.int    ; New Reno Generic Scientist
{425}{}{머크}                           # SCMerk.int      ; Merk an NCR mob type guy
{426}{}{팬}                            # ncBoxFan.int    ; New Reno Boxing Fan
{427}{}{마약상}                    # ncDrgDlr.int    ; New Reno Drug Dealer
{428}{}{카지노 손님}                  # ncCasPat.int    ; New Reno Casino Patron
{429}{}{포주}                           # ncPimp.int      ; New Reno Generic Pimp
{430}{}{마약쟁이}                         # ncJunkie.int    ; New Reno Generic Junkie
{431}{}{가구}                      # stuff.int       ; signals critters on steal attempt
{432}{}{바닥}                          # trespass.int    ; same as stuff only for an area
{433}{}{땅 바닥}                         # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{홀로디스크}                       # SIFakhlo.int    ; Fake holodisk you get from Merk in NCR.
{435}{}{레니}                          # SCLenny.int     ; Lenny a guy in NCR Entrance
{436}{}{상자}                            # SCPtbox.int     ; Players temp box to hold his stuff for the fight with lenny
{437}{}{매춘부}                     # ncProsti.int    ; New Reno Prostitute with billions of messages
{438}{}{노예}                          # ncSlave.int     ; New Reno Slaves
{439}{}{리코}                           # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{포르노 여배우}                   # ncActres.int    ; New Reno Porn Actress
{441}{}{플러퍼}                        # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{지도 스크립트}                     # Klacanyn.int    ; Map script for Klamath Canyon
{443}{}{늑대}                           # ECWlfPck.int    ; Military Base Wolf Pack
{444}{}{발전기}                      # ESPwrGen.int    ; Military Base Power Generator
{445}{}{문}                           # ESLkDor.int     ; Military Base Locked Door (-30)
{446}{}{슈퍼 뮤턴트}                   # ECGenMut.int    ; Military Base Generic Mutant
{447}{}{살바토레의 부하}                # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{비숍의 부하}                   # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{모르디노의 부하}                  # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{라이트의 자식}                 # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{카지노 문지기}                 # ncCasBou.int    ; New Reno Generic Casino Bouncer
{452}{}{미라}                           # SCMira.int      ; NCR entrance bartender
{453}{}{뉴 레노 버진 스트리트}         # NewR1.int       ; New Reno Map Virgin Street
{454}{}{뉴 레노 2번가}            # NewR2.int       ; New Reno Map 2nd Street
{455}{}{뉴 레노 상업로}        # NewR3.int       ; New Reno Map Commercial Row
{456}{}{뉴 레노 동부 지구}             # NewR4.int       ; New Reno Map East Side
{457}{}{뉴 레노 마구간}               # NewRSt.int      ; New Reno Map Stables
{458}{}{뉴 레노 폐차장}             # NewRCS.int      ; New Reno Map Chop Shop
{459}{}{뉴 레노 골고다}              # NewRGo.int      ; New Reno Map Gologtha
{460}{}{뉴 레노 비숍 지하실}       # NewRBa.int      ; New Reno Map Bishop Basement
{461}{}{홀로디스크}                       # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{홀로디스크}                       # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{홀로디스크}                       # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{홀로디스크}                       # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{홀로디스크}                       # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{경비}                          # SCGteGrd.int    ; Ncr gate guard
{467}{}{광산차}                      # ESMinCrt.int    ; Military Base Mine Cart to explode on door
{468}{}{멜콰이어}                       # ECMelchr.int    ; Melchoir the Magnificent (pseudo-mage)
{469}{}{돌연변이 짐승}                  # ECMutRat.int    ; Mutated Rats in Military Base
{470}{}{FEV 끈적이는 물질}                        # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{경비 대장}                  # SCGGCap.int     ; NCR Entrance Gate guard captain
{472}{}{노예 감독관}                 # SCslvovr.int    ; NCR Entrance slave overseer
{473}{}{멜콰이어의 애완동물}                 # ECMelPet.int    ; Melchior's Pets
{474}{}{노예상 경비}                   # SCslvgrd.int    ; Slaver Guard in NCR Entrance
{475}{}{문}                           # SIclsdor.int    ; Closing door
{476}{}{단말기}                       # SITerm.int      ; Slave pen terminals NCR Entrance
{477}{}{슬롯 머신}                   # ziSlots.int     ; Generic Slot Machine
{478}{}{아이}                          # ncWriChi.int    ; New Wright children
{479}{}{쉡}                           # ncSheb.int      ; New Reno Sheb
{480}{}{경비}                          # SCMrkGrd.int    ; Merk's guards NCR Entrance and council
{481}{}{발생기}                        # SIEmtr.int      ; Emitter in NCR Entrance
{482}{}{역장}                    # SIFField.int    ; Force field in NCR Entrance
{483}{}{슐릭}                          # Kcsulik.int     ; Sulik from Klamath
{484}{}{헨리 박사}                      # SCHenry.int     ; Henry NCR Entrance
{485}{}{경비}                          # SCCarGrd.int    ; Carlson's guards NCR2
{486}{}{칼슨 경비대 공격}          # STCaratk.int    ; Carlson's guards attack spatial
{487}{}{칼슨의 입구 경비}          # SCcgtgrd.int    ; Carlson's gate Guards
{488}{}{죄수}                       # VCOutPrs.int    ; Vault City Outsider Prisoner (Generic)
{489}{}{죄수}                       # VCCitPrs.int    ; Vault City Citizen Prisoner (Generic)
{490}{}{시민}                        # VCGenFam.int    ; Vault City Generic Family
{491}{}{편의 시설}                  # VCAmAid.int     ; Vault City Amenities Aid
{492}{}{접수처 경비}                     # GCRDesk.int     ; Gecko Reactor Desk Guard
{493}{}{구울 인부}                   # GCRGhoul.int    ; Gecko Reactor Ghoul Worker
{494}{}{발광 구울}                    # GCRGlow.int     ; Gecko Glowing One
{495}{}{구울 경비}                    # GCRGuard.int    ; Gecko Red Door Guard
{496}{}{로봇}                          # GCRobot.int     ; Gecko Reactor Robot
{497}{}{구울}                          # GCFolk.int      ; Gecko Townsfolk
{498}{}{숭배자}                     # GCWorshp.int    ; Gecko Worshippers
{499}{}{해롤드}                         # GCHarold.int    ; Harold in Gecko
{500}{}{Officer}                        # GCPACOff.int    ; Gecko Powered Armor Com Officer
{501}{}{토토}                           # SCToto.int      ; Toto hlper bot in NCR 1
{502}{}{도로시}                        # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{마을사람}                    # ncPerson.int    ; New Reno Generic Townsperson/Citizen
{504}{}{구울 경비}                    # GCYGuard.int    ; Gecko Yellow Door Guard
{505}{}{구울 경비}                    # GCGuard.int     ; Gecko Generic Guard
{506}{}{곤드}                           # SCGond.int      ; Ranger Guard, NCR 1
{507}{}{더포}                          # SCDuppo.int     ; Stockman's yard store owner
{508}{}{물건}                          # SIdtbl.int      ; Duppo's tables in shop
{509}{}{밥}                            # SCsalbob.int    ; Salt Beef Bob NCR 3
{510}{}{카지노 걸}                    # ziDceGrl.int    ; Generic Casino Girl with Dice Game
{511}{}{카지노 걸}                    # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{마법의 8번 공}               # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{브라민}                        # ncAngBra.int    ; New Reno Angry Brahmin
{514}{}{슬롯 머신}                   # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{노인 맥기}                  # ncMcGee.int     ; New Reno Old Man (Bobby) McGee
{516}{}{쓰리 카드 몬테}               # nc3Monte.int    ; New Reno Three Card Monte
{517}{}{알게논}                       # ncAlgern.int    ; New Reno Algernon
{518}{}{빌}                           # ncBill .int     ; New Reno Bill (Trees Lounge)
{519}{}{경호원}             # ncBisGrd.int    ; New Reno Bishop's Bodyguards
{520}{}{존 비숍}                    # ncBishop.int    ; New Reno John Bishop
{521}{}{카지노 머신}                 # niCasMac.int    ; New Reno Casino Machine
{522}{}{불법 카센터 보이}                  # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{크리스 라이트}                   # ncChrWri.int    ; New Reno Chris Wright
{524}{}{코디}                           # ncCody .int     ; New Reno Cody
{525}{}{코르시카인 형제}                # ncCorBro.int    ; New Reno Corsican Bothers
{526}{}{엘드리지}                       # ncEldrid.int    ; New Reno Eldridge
{527}{}{에틸 라이트}                   # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{툴리 신부}                   # ncFTully.int    ; New Reno Father Tully
{529}{}{험퍼덤퍼디도}               # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{리틀 지저스 모르디노}             # ncLilJes.int    ; New Reno Lil' Jesus Mordino
{531}{}{재기드 지미 J}                 # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{키스 라이트}                   # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{리 앤 비숍}                # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{미소년 로이드}               # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{메이슨}                          # ncMason.int     ; New Reno Mason
{536}{}{경비}                          # ncMyrGrd.int    ; New Reno Myron's Guards
{537}{}{마이론}                          # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{니키}                          # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{오빌 라이트}                 # ncOrvill.int    ; New Reno Orville Wright
{540}{}{감독자}                       # ncPitBos.int    ; New Reno Generic Pit Boss
{541}{}{로켓 맨 르네스코}         # ncRenesc.int    ; New Reno Renesco the Rocket-Man
{542}{}{마저리 리드}                  # ncResear.int    ; New Reno Stables Researcher
{543}{}{보스 살바토레}                 # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{스튜어트 리틀}                  # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{T-레이}                          # ncTRay .int     ; New Reno T-Ray
{546}{}{창녀}                          # ncBitch.int     ; New Reno Corsican Brothers Bitches
{547}{}{라이트가 어린이}                   # ncWriPly.int    ; New Reno Wright Children Playing
{548}{}{NCR 경찰}                     # SCCop.int       ; NCR cop
{549}{}{오스왈드}                         # SCOswald.int    ; Raider Oswald captive NCR 1
{550}{}{더스티}                          # SCDusty.int     ; Dusty bartender in NCR 1
{551}{}{쥴스}                          # ncJules.int     ; New Reno Jules
{552}{}{키티 양}                     # ncKitty.int     ; New Reno Miss Kitty
{553}{}{바텐더}                      # ncBarten.int    ; New Reno Bartender
{554}{}{부관 칼}                    # SCKarl.int      ; NCR Deputy
{555}{}{창살 문}                      # SIKdoor.int     ; NCR Cell door
{556}{}{빅 지저스 모르디노}              # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{호스}                           # SCHoss.int      ; Hoss, bully NCR 1 map
{558}{}{변이원 혈청}                # SIMserum.int    ; Mutagenic Serum
{559}{}{상자}                            # niSalBox.int    ; New Reno Salvatore Bartender Shop Inventory
{560}{}{상자}                            # niMorBox.int    ; New Reno Mordino Bartender Shop Inventory
{561}{}{상자}                            # niBisBox.int    ; New Reno Bishop Bartender Shop Inventory
{562}{}{상자}                            # niTmpBox.int    ; New Reno Personal Inventory Swap Box
{563}{}{주빌리 박사}                 # SCDocJub.int    ; Doctor Jubilee NCR Map 1
{564}{}{문}                           # GSYDoor.int     ; Yellow Door in Gecko Reactor
{565}{}{문}                           # GSRDoor.int     ; Red Door in Gecko Reactor
{566}{}{책장}                       # SIdshelf.int    ; Bookshelf for the Doc NCR 1
{567}{}{보안관 뒤몽}                 # SCsherif.int    ; Sheriff in NCR map 1
{568}{}{엘리스}                          # SCElise.int     ; Elise in NCR map 1 ranger leader chick
{569}{}{목장 노동자}                     # SCwrHand.int    ; Westin Ranch Hand NCR 3
{570}{}{펠릭스}                          # SCFelix.int     ; Westin's forman on NCR 3
{571}{}{웨스틴}                         # SCWestin.int    ; Westin big dude on NCR 3
{572}{}{론도}                          # SCRondo.int     ; Rondo Ranger NCR 1
{573}{}{로봇개}                        # SCRobo.int      ; Robodog NCR 1
{574}{}{계단}                         # NIBissta.int    ; New Reno Bishop's stairs
{575}{}{할}                            # SCHal.int       ; Hal, Drive Leader
{576}{}{군터}                        # SCGunthr.int    ; Gunther Tandi's assistant NCR 2
{577}{}{브라민}                        # ECCrtBra.int    ; Random Encounter Brahmin for carts
{578}{}{행상 단장}                 # ECCvnMst.int    ; Random Encounter Caravan Master
{579}{}{행상 기사}                 # ECCvnDrv.int    ; Random Encounter Caravan Driver
{580}{}{행상 경비}                  # ECCvnGrd.int    ; Random Encounter Caravan Guard
{581}{}{레이더}                         # ECRadLdr.int    ; Random Encounter Raider Leader
{582}{}{조직 폭력배}                        # ECMobstr.int    ; Random Encounter Mobster (Outside New Reno)
{583}{}{사냥꾼}                         # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{사냥꾼}                         # ECHunter.int    ; Random Encounter Hunting Party
{585}{}{레인저}                         # ECRanger.int    ; Random Encounter NCR Rangers (Patrol)
{586}{}{용병}                      # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{용병}                      # ECMrcLdr.int    ; Random Encounter Mercenary Leader
{588}{}{레이더}                         # ECRadGrp.int    ; Random Encounter Raider Party
{589}{}{행상 기사}                 # ECRndDrv.int    ; Random Encounter Other Caravan Driver
{590}{}{행상 경비}                  # ECRndGrd.int    ; Random Encounter Other Caravan Guard
{591}{}{순찰대}                   # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{순찰대 대장}                 # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{농부}                         # ECFarmer.int    ; Random Encounter Farmer
{594}{}{브라민}                        # ECBraHrd.int    ; Random Encounter Brahmin Herd
{595}{}{브라민}                        # ECLedBra.int    ; Random Encounter Lead Brahmin
{596}{}{여행자}                       # ECTrvlr.int     ; Random Encounter Traveler
{597}{}{순찰대}                   # ECGhlPat.int    ; Random Encounter Ghoul Patrol
{598}{}{순찰대 대장}                 # ECGhlCpt.int    ; Random Encounter Ghoul Patrol Capt.
{599}{}{순찰대}                   # ECMutPat.int    ; Random Encounter Mutant Patrol
{600}{}{순찰대 대장}                 # ECMutCpt.int    ; Random Encounter Mutant Patrol Capt.
{601}{}{브라민 몰이꾼}                 # ECBraDrv.int    ; Random Encounter Brahmin Driver
{602}{}{가축 도둑}                        # ECBraRst.int    ; Random Encounter Brahmin Rustler
{603}{}{무단 거주자}                       # ECSquatr.int    ; Random Encounter Squatters
{604}{}{노예 폐지론자}                   # ECAbolst.int    ; Random Encounter Abolitionist
{605}{}{주류 밀수업자}                     # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{슈퍼 뮤턴트}                   # ECRogMut.int    ; Random Encounter Rogue Super Mutants
{607}{}{낚시꾼}                      # ECFshrmn.int    ; Random Encounter Fisherman
{608}{}{노예상인}                         # ECSlaver.int    ; Random Encounter Slaver
{609}{}{사냥꾼}                        # ECTrappr.int    ; Random Encounter Trapper
{610}{}{칼슨의 아이}                  # SCCarkid.int    ; Carlson's kid NCR map 2
{611}{}{칼슨}                        # SCCarlsn.int    ; Carlson NCR 2
{612}{}{}                               # Animfrv.int     ; Animate forever
{613}{}{경관 잭}                   # SCOfjack.int    ; Officer Jack NCR 1
{614}{}{깨우친 자}            # SCEnlOne.int    ; The Enlightened One NCR 1
{615}{}{문}                           # diDoor.int      ; Den Auto Closing Door
{616}{}{컴퓨터}                       # GsTerm.int      ; Gecko robot control terminal
{617}{}{브라민}                         # SCBrahmn.int    ; NCR Map 4 Brahmin.
{618}{}{데스클로}                      # SCDthcla.int    ; NCR Map 4 Deathclaw.
{619}{}{탈출 그리드}                      # SIExit.int      ; NCR Map 4 Exit Grid control
{620}{}{컴퓨터}                       # SSComp.int      ; NCR Map 1 computer terminal that blows up
{621}{}{퍼거스}                        # SCFergus.int    ; NCR Map 2
{622}{}{아리엘}                          # OCAriel.int     ; Vault 13 Ariel
{623}{}{패니 매}                     # RCFannie.int    ; Fannie Mae the hooker in Redding
{624}{}{컴퓨터 단말기}              # OCComptr.int    ; Computer terminal in Vault 13
{625}{}{달리아}                          # OCDalia.int     ; Dalia in Vault 13
{626}{}{다르}                            # OCDar.int       ; Dar Deathclaw guard Vault 13
{627}{}{데이브}                           # OCDave.int      ; Dave NPC in Vault 13
{628}{}{고든}                         # OCGordon.int    ; Gordon the shrine temple dude
{629}{}{폐업 간판}           # ziClosed.int    ; Generic "Out of Business" signs
{630}{}{원자로 제어기}      # gsReactr.int    ; Script to animate reactor
{631}{}{지미}                          # OCJimmy.int     ; Jimmy guy in computer room Vault 13
{632}{}{조셉}                         # OCJoseph.int    ; The Doctor in Vault 13
{633}{}{맷}                           # OCMatt.int      ; Matt prisonner in Vault 13
{634}{}{}                               # RCFitRat.int    ; Redding Fighting Molerats
{635}{}{지도 스크립트}                     # RedMEnt.int     ; Redding Mine Entrance Map Script
{636}{}{V13 지도 스크립트}                 # vault13.int     ; Vault13 map script
{637}{}{샌디}                          # OCSandy.int     ; Sandy Vault 13 child.
{638}{}{상자}                            # ziTmpBox.int    ; Generic Temporary swap box
{639}{}{써언}                         # OCThearn.int    ; Vault 13 Guard Thearn.
{640}{}{상자}                            # miGriBox.int    ; Modoc Grisham Merchant box
{641}{}{상자}                            # miJoBox.int     ; Modoc Jo Merchant box
{642}{}{발디스}                         # OCValdis.int    ; Valdis guard in Vault 13
{643}{}{컴퓨터 단말기}              # OSvdrcmp.int    ; Door computer vault 13 entrance
{644}{}{금속 락커}                   # OILocker.int    ; Metal locker in Vault 13
{645}{}{풋락커}                     # OIftlkr.int     ; Footlocker in Vault 13
{646}{}{데스클로 경비}                # OCgrunt.int     ; Generic Vault 13 Deathclaw guard
{647}{}{고리스}                          # OCGoris.int     ; Goris possible party NPC vault 13
{648}{}{상자}                            # miBalBox.int    ; Modoc Balthas Merchant box
{649}{}{금속 락커}                   # siLocker.int    ; Guard's lockers in NCR 1
{650}{}{치트 캐릭터}                        # Cheater.int     ; Cheater Character
{651}{}{V15 지도 스크립트}                 # vault15.int     ; Vault 15 map script
{652}{}{필}                           # bcPhil.int      ; Phil the secret vault 15 entrance guard
{653}{}{빌}                           # bcBill.int      ; Bill in Vault 15 Entrance
{654}{}{도살자}                        # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{달리아}                          # bcDalia.int     ; Guard who guards a trail and shows up in v13
{656}{}{존}                           # bcJohn.int      ; Vault 15 guy entrance
{657}{}{존스}                          # BCJones.int     ; Vault 15 doctor
{658}{}{카를라}                          # BCKarla.int     ; Karla Vault 15 guard.
{659}{}{V15 비밀 입구 지도}        # V15sent.int     ; Vault 15 secret entrance map
{660}{}{레베카}                        # BCRebecc.int    ; Vault 15 Rebecca
{661}{}{문}                           # miDoor.int      ; Modoc Doors
{662}{}{데스 클로}                      # mcDthClw.int    ; Modoc Rose's "Chicken"
{663}{}{로베르타}                        # bcRobert.int    ; Roberta Vault 15 Entrance
{664}{}{사라}                           # bcSara.int      ; Sara vault 15 Entrance
{665}{}{지크}                           # bcZeke.int      ; Zeke vault 15 Entrance mayor dude
{666}{}{브라민}                        # bcBrahmn.int    ; Generic Brahmin in Vault15 Entrance
{667}{}{나무 문}                      # BiEntDr.int     ; Trapped Vault15 entrance door
{668}{}{크리시}                        # BCCrissy.int    ; Crissy, Rebecca's daughter
{669}{}{다리온}                         # BCDarion.int    ; Big bad dude in Vault 15
{670}{}{다리온의 경비}                 # BCDargrd.int    ; Darion's guard in Vault 15
{671}{}{다리온의 개}                   # BCDardog.int    ; Darion's dog in Vault 15
{672}{}{캐시디}                        # VCCasidy.int    ; Cassidy the  bar person in Vault City
{673}{}{우물}                           # miWell.int      ; Modoc Well
{674}{}{두더지쥐}                       # mcMolRat.int    ; Modoc Shitter Mole Rat
{675}{}{브라민 토막}                  # miBraMea.int    ; Modoc Brahmin Chunks
{676}{}{브라민}                        # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{승강기 문}                  # bsElev.int      ; Elevator door in V15sent
{678}{}{개}                            # mcKilDog.int    ; Modoc Dog that hangs out at the slaughter house
{679}{}{쥐}                            # mcRat.int       ; Modoc Garden Rat
{680}{}{선 스팟}                       # ziSunSpt.int    ; Generic Sun Spot
{681}{}{베스}                           # mcBess.int      ; Modoc Bess the Brahmin
{682}{}{상자}                            # miJkyBox.int    ; Modoc Jerky box
{683}{}{크랩스 딜러}                   # zcCrpDel.int    ; Craps Dealer
{684}{}{볼트 15 경비}                 # bcGenGrd.int    ; Vault 15 Khan Guard
{685}{}{슬래그}                           # mcSlag.int      ; Modoc Generic Slag
{686}{}{Rug}                            # mtRug.int       ; Modoc Spacial Script for Rug
{687}{}{아이}                          # mcChild.int     ; Modoc Child
{688}{}{에일린}                         # hcAileen.int    ; Aileen in Broken Hills
{689}{}{경비}                          # hcBnkGrd.int    ; Bank Guard in Broken Hills
{690}{}{홀리데이 박사}                    # hcDoc.int       ; Doc in Broken Hills
{691}{}{심복}                       # hcencha.int     ; Henchman A in Broken Hills
{692}{}{심복}                       # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{여성}                          # hcfemale.int    ; Female in Broken Hills
{694}{}{프랜시스}                        # hcFranci.int    ; Francis in Broken Hills
{695}{}{프랭크}                          # hcFrank.int     ; Frank in Broken Hills
{696}{}{구울}                          # hcGhoul.int     ; Ghoul in Broken Hills
{697}{}{리즈}                            # hcLiz.int       ; Liz in Broken Hills
{698}{}{남성}                            # hcmale.int      ; Male in Broken Hills
{699}{}{맨슨}                         # hcManson.int    ; Manson in Broken Hills
{700}{}{마커스}                         # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{광부}                          # hcMiners.int    ; Miners in Broken Hills
{702}{}{뮤턴트}                         # hcMutant.int    ; Mutant in Broken Hills
{703}{}{빌}                           # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{필}                           # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{스티브}                          # hcSteve.int     ; Steve in Broken Hills
{706}{}{감독관}                     # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{자이우스}                          # hcZaius.int     ; Zaius in Broken Hills
{708}{}{제이콥}                          # hcJacob.int     ; Jacob in Broken Hills
{709}{}{화학실험용품}                  # hchems.int      ; Chemistry Set in Broken Hills
{710}{}{소품}                           # miGstPrp.int    ; Modoc Ghost Farm Prop
{711}{}{문}                           # bssdor1.int     ; Shack doors on V15sEnt map
{712}{}{컴퓨터}                       # BSComp1.int     ; Library Computer Vault 15
{713}{}{차드}                           # hcchad.int      ; Chad from Broken Hills
{714}{}{포자 식물}                    # ECPlant.int     ; Random Encounter Spore Plant
{715}{}{}                               # ECGecko.int     ; Random Encounter Gecko
{716}{}{방사능전갈}                    # ECScorp.int     ; Random Encounter Scorpions
{717}{}{}                               # ECRat.int       ; Random Encounter Rats
{718}{}{전사}                        # ECWarPty.int    ; Random Encounter War Party
{719}{}{식인종}                       # ECCanibl.int    ; Random Encounter Cannibals
{720}{}{추방자}                        # ECOutCst.int    ; Random Encounter Outcasts
{721}{}{신도}                    # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{유목민}                          # ECNomad.int     ; Random Encounter Nomads
{723}{}{노숙자}                # ECHomles.int    ; Random Encounter Homeless
{724}{}{도적}                         # ECBandit.int    ; Random Encounter Bandit
{725}{}{강도}                         # ECRobber.int    ; Random Encounter Robber
{726}{}{노상강도}                     # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{노예상인}                         # ECSlvRun.int    ; Random Encounter Slavers on a Slave Run
{728}{}{노예}                          # ECSlave.int     ; Random Encounter Slaves
{729}{}{파티객}                        # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{사마귀}                         # ECMantis.int    ; Random Encounter Mantis
{731}{}{브라민}                        # ECBrahmn.int    ; Random Encounter Brahmin
{732}{}{들개}                       # ECWldDog.int    ; Random Encounter Wild Dogs
{733}{}{컴퓨터}                       # BSComp2.int     ; Darion's computer terminal Vault15
{734}{}{컴퓨터}                       # BSComp3.int     ; Force field computer terminal
{735}{}{컴퓨터 단말기}              # BSComp4.int     ; Force Field control computer by entrance Vault 15
{736}{}{컴퓨터}                       # BSComp5.int     ; Computer at the Power area. Vault 15
{737}{}{발전기}                # BSPower.int     ; Power Generator in Vault 15
{738}{}{역장}                    # BSField.int     ; Force Field in Vault 15
{739}{}{소농민}                        # mcPeasan.int    ; Modoc Peasant Person
{740}{}{발생기}                        # bsEmtr.int      ; Emitter in Vault 15
{741}{}{볼트 문}                     # osv13dr.int     ; Vault 13 Door
{742}{}{보안 문}                  # osDoor1.int     ; Vault 13 Door that shows deathclaws
{743}{}{베스 조우}                 # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{베스}                           # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{브라민}                        # ECBesCow.int    ; One of the Brahmin in Bess's herd
{746}{}{안젤라 비숍}                  # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{"쌍방울" 토미}              # ncTommy.int     ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{금고}                           # niABisSf.int    ; New Reno Angela Bishop's Safe
{749}{}{금고}                           # niMrBSf.int     ; New Reno Mr. Bishop's Safe
{750}{}{금고}                           # niMrsBSf.int    ; New Reno Mrs. Bishop's Safe
{751}{}{금고}                           # niOWriSf.int    ; New Reno Orville Wright's Safe
{752}{}{무덤}                          # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{서랍장}                        # niWridrs.int    ; New Reno Richard Wright's Dresser
{754}{}{무덤}                          # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{증류기}                          # niWriSti.int    ; New Reno Wright Stills
{756}{}{라미레즈}                        # ncRamire.int    ; New Reno Ramirez
{757}{}{동굴 1 무작위 조우 지도}    # cave01.int      ; Cave 1 Random Encounter Map
{758}{}{상자}                            # niRenBox.int    ; New Reno Renesco Box
{759}{}{문}                           # niDoor.int      ; New Reno Door
{760}{}{동굴 2 무작위 조우 지도}    # cave02.int      ; Cave 2 Random Encounter Map
{761}{}{동굴 3 무작위 조우 지도}    # cave03.int      ; Cave 3 Random Encounter Map
{762}{}{동굴 4 무작위 조우 지도}    # cave04.int      ; Cave 4 Random Encounter Map
{763}{}{동굴 2 무작위 조우 지도}    # cave02.int      ; Cave 2 Random Encounter Map
{764}{}{문}                           # VIEntDor.int    ; Vault City Entrance Door
{765}{}{지도 스크립트}                     # VCtyDwtn.int    ; Vault City Downtown Map script
{766}{}{함정문}                      # miTrpDor.int    ; Modoc Ghost Farm Trap Door
{767}{}{Lockbox}                        # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{방}                           # ntLydRom.int    ; New Reno Lloyd Room
{769}{}{토마스 무어}                   # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{문}                           # ZILckDor.int    ; Generic Locked Door (-20)
{771}{}{락커}                         # niLydBox.int    ; New Reno Lloyd's Loot Box
{772}{}{맨홀}                        # niManhol.int    ; New Reno Manhole to Lloyd's Loot
{773}{}{무덤}                          # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{보급품 경비}                   # VCSupGrd.int    ; Vault City Supply Guard Martin
{775}{}{지도 스크립트}                     # broken1.int     ; Map Script for Broken Hills Map 1
{776}{}{지도 스크립트}                     # rndexcow.int    ; Map Script for Low Luck encounter
{777}{}{성난 브라민}                    # eccowbmb.int    ; The cows that blow
{778}{}{헤익스윌}                      # RCHakes.int     ; Hakeswill from Redding
{779}{}{레딩 시내}               # REDDown.int     ; Redding Downtown map script
{780}{}{맵 스크립트}                     # BHRndDst.int    ; Broken Hills Caravan Desert Map
{781}{}{맵 스크립트}                     # BHRndMtn.int    ; Broken Hills Caravan Mountain Map
{782}{}{루}                            # RCLou.int       ; Lou from Redding
{783}{}{아서}                         # ECArthur.int    ; Arthur the leader of the Special Encounter knights
{784}{}{로빈}                          # ECRobin.int     ; Robin one of the Knights with Arthur
{785}{}{베데미어}                        # ECBedemi.int    ; Bedemir one of the Knights with Arthur
{786}{}{란슬롯 경}                  # ECSirLau.int    ; Sir Launcelot one of the Knights with Arthur
{787}{}{갤러해드}                        # ECGalaha.int    ; Galahad one of the knights with Arthur
{788}{}{벤 웨이드}                       # RCWade.int      ; Ben Wade from Radding
{789}{}{애서배스카 딕}                 # RCDick.int      ; Athabaska Dick from Redding
{790}{}{과부 루니}                   # RCRooney.int    ; Widow Rooney from Redding
{791}{}{마을사람}                    # RCGenPes.int    ; Generic Townsperson in Redding
{792}{}{스탠웰}                       # RCStanwl.int    ; Stannwell from Redding
{793}{}{사비넬리}                      # RCSavine.int    ; Savinelli from Redding
{794}{}{마지}                          # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{모제스카 부인}                 # RCModjes.int    ; Madam Modjeska from Redding
{796}{}{제임스 호피}                    # RCHoffy.int     ; James Hoffy, Caravan Master for Redding
{797}{}{맵 스크립트}                     # Rndholy1.int    ; Random Encounter Holy Knights 1 map
{798}{}{팻시}                          # ECPatsy.int     ; Arthur's horse HOLY 1 encounter
{799}{}{콩코드}                       # ECConcor.int    ; Concord Launcelot's horse.
{800}{}{에릭}                           # ECEric.int      ; Robin's horse
{801}{}{존}                           # ECJohn.int      ; Bedemir's horse
{802}{}{조슈아}                         # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{사다리}                         # miLadder.int    ; Modoc Shitter Ladder
{804}{}{거대한 머리}                       # ecBHead.int     ; Big Head special encounter
{805}{}{흑인 남주인공}                     # ecBlkHro.int    ; Black Hero model
{806}{}{적발 여주인공}                    # ecRedHro.int    ; Red Heroine model
{807}{}{Set}                            # ecSet.int       ; Set in Cafe of Broken Dreams
{808}{}{탠디}                          # ecTandi.int     ; Tandi in Cafe of " "
{809}{}{백인 남주인공}                     # ecWhro1.int     ; White Hero Model 1 " " "
{810}{}{백인 남주인공}                     # ecWhro2.int     ; White Hero Model 2 " " "
{811}{}{백인 여주인공}                  # ecWheon1.int    ; White Heroine Model 1
{812}{}{상자}                            # NiJulBox.int    ; New Reno Jules Shop Inventory Box
{813}{}{상자}                            # niEldBox.int    ; New Reno Eldridge Shop Box
{814}{}{상자}                            # niEldBx2.int    ; New Reno Eldridge Shop Box (For Made Men)
{815}{}{맵 스크립트}                     # rndholy2.int    ; Hi-Luck random Holy knight encounter 2
{816}{}{보팔 쥐}                     # ECVorRat.int    ; Vorpal Rat for Holy Knight 2
{817}{}{개}                            # ECPDog.int      ; Pariah Dog... not good to have following you around
{818}{}{훈련부사관}                 # CCDrill.int     ; Drill Seargant in Colusa/Nevarro
{819}{}{경비}                          # CCGuard.int     ; Guard in Colusa/Nevarro
{820}{}{기술자}                     # CCTech.int      ; Technician in Colusa/Nevarro
{821}{}{사령관}                      # CCMandr.int     ; Commander in Colusa Nevarro
{822}{}{크리스}                          # CCChris.int     ; Chris the gas station attendant in Colusa
{823}{}{병참 장교}                 # CCMaster.int    ; Quarter Master in Colusa/Nevarro
{824}{}{경비}                          # CCGGuard.int    ; Gate Guard in Colusa/Nevarro
{825}{}{무덤}                          # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Spacial Script)
{826}{}{자동차}                            # ntCar1.int      ; New Reno Stolen Car Seed Spacial 1
{827}{}{자동차}                            # ntCar2.int      ; New Reno Stolen Car Seed Spacial 2
{828}{}{무덤}                          # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{로브를 입은 사람}                   # EcBridge.int    ; Bridge guy special encounter
{830}{}{소 구매자}                   # SCdrvpay.int    ; Cattle drive from NCR to redding.
{831}{}{맵 스크립트}                     # RndBridg.int    ; Random Bridge encounter
{832}{}{신비로운 이방인}            # ECMstStr.int    ; Mysterious Stranger
{833}{}{성난 브라민}                    # ECgcwbmb.int    ; Generic Cow bomb
{834}{}{야쿠자 일원}                  # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{야인}                         # ECWilder.int    ; Random Encounter Wilder
{836}{}{개}                            # ncWriDog.int    ; New Reno Wright Dog
{837}{}{상자}                            # niRamBox.int    ; New Reno Box to be delivered to Ramirez
{838}{}{순찰대 일원}                  # ECUniPat.int    ; Unity Patrol Random Encounter
{839}{}{여행자}                       # ECTravlr.int    ; Random Encounter Travler
{840}{}{스모크}                          # KtSmoke.int     ; displays message about smoke smell in Duntons
{841}{}{상인}                         # ECTrader.int    ; Random Encounter Trader
{842}{}{시체청소부}                      # ECScaven.int    ; Random Encounter Scavenger
{843}{}{무역상}                       # FCMercha.int    ; San Fran Air bag merchant
{844}{}{소농민}                        # FCBadPea.int    ; San Fran Bad Peasants
{845}{}{아로요 사원}                  # ARTemple.int    ; Arroyo Temple map script
{846}{}{항만 노동자}                    # FCDokWrk.int    ; San Fran Dock Worker
{847}{}{소농민}                        # FCGudPea.int    ; San Fran Good Peasants
{848}{}{「시」 경비}                      # FCShiGrd.int    ; San Fran Shi Guard
{849}{}{카메론}                        # ACTemVil.int    ; Temple challenge person
{850}{}{문}                           # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{클린트}                          # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{농작물}                          # AICrops.int     ; Crops that die after a period of time
{853}{}{「시」 실험실 기술자}                   # FCslabte.int    ; San Fran Shi Lab techs
{854}{}{아이}                          # FCSkids.int     ; San Fran Shi Kids
{855}{}{구울}                          # GCWander.int    ; wandering ghouls in Gecko
{856}{}{풍 박사}                       # FCDrFung.int    ; San Fran Dr Fung
{857}{}{쥴}                            # OCJul.int       ; Vault 13 Denmother Guard
{858}{}{케릿}                         # OCKerith.int    ; Vault 13 Den Mother
{859}{}{상자}                          # AITemCst.int    ; Temple Chest to hold the players things
{860}{}{구울}                          # GCRGhul.int     ; Reactor ghoul that doesn't move
{861}{}{}                               # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                               # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{탐사자}                     # ECProspe.int    ; Random Encounter Prospector
{864}{}{폭력단 일원}                    # ECPrsGng.int    ; Random Encounter Press Gang
{865}{}{유목민 통솔자}                    # ECNomChf.int    ; Random Encounter Nomad Chief
{866}{}{허볼로지스트}                     # ECElRon.int     ; Hubologist Patrol
{867}{}{미치광이}                          # ECCrazy.int     ; Crazies from Random Encounter
{868}{}{무단 거주자}                   # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{식인종}                       # ECCanbal.int    ; Random Encounter Cannibals
{870}{}{유목민 주술사}                   # ECNomSha.int    ; Random Encounter Nomad Shamon
{871}{}{약탈자}                       # ECMaradr.int    ; Random Encounter Marauder
{872}{}{도적}                          # ECRogue.int     ; Random Encounter Rogue
{873}{}{허미트}                         # ECHermit.int    ; Random Encounter Hermit
{874}{}{}                               # ECGangs.int     ; Random Encounter Gangs
{875}{}{행상 단장}                 # ECMstKla.int    ; Random Encounter Klamath Caravan Master
{876}{}{행상 단장}                 # ECMstDen.int    ; Random Encounter Den Caravan Master
{877}{}{행상 단장}                 # ECMstNew.int    ; Random Encounter New Reno Caravan Master
{878}{}{행상 단장}                 # ECMstRed.int    ; Random Encounter Redding Caravan Master
{879}{}{행상 단장}                 # ECMstBro.int    ; Random Encounter Broken Hills Caravan Master
{880}{}{행상 단장}                 # ECMstGec.int    ; Random Encounter Gecko Caravan Master
{881}{}{행상 단장}                 # ECMstSan.int    ; Random Encounter San Fran Caravan Master
{882}{}{행상 단장}                 # ECMstNCR.int    ; Random Encounter NCR Caravan Master
{883}{}{행상 단장}                 # ECMstV15.int    ; Random Encounter Vault 15 Caravan Master
{884}{}{농부의 아내}                  # ECFrmWfe.int    ; Random Encounter Farmer's wife
{885}{}{농부의 아이}                   # ECFrmKid.int    ; Random Encounter Farmer's Kid
{886}{}{정착민}                    # ECHomest.int    ; Random Encounter Homesteader
{887}{}{정착민의 아내}             # ECHomwfe.int    ; Random Encounter Homesteader's Wife
{888}{}{정착민의 아이}              # ECHomKid.int    ; Random Encounter Homesteader's Kid
{889}{}{행상 단장}                 # ECMstVC.int     ; Random Encounter Vault City Caravan Master
{890}{}{}                               # ECAlien.int     ; Random Encounter Alien
{891}{}{}                               # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                               # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                               # ECCentur.int    ; Random Encounter Centaurs
{894}{}{엔클레이브 순찰대원}              # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{용병 대장}                   # icMrcCpt.int    ; Raiders Merc Captain
{896}{}{용병 레이더}                    # icMerc.int      ; Raiders Merc
{897}{}{"배회하는-그림자"}             # icScout.int     ; Raiders Scout
{898}{}{금고}                           # iiSafe.int      ; Raiders Safe
{899}{}{}                               # raiders1.int    ; Raiders 1 Enterance
{900}{}{}                               # raiders2.int    ; Raiders 2 Caves
{901}{}{}                               # HSCellDr.int    ; Broken Hills bank/jail door
{902}{}{상자}                            # niTRyBox.int    ; New Reno Chop Shop T-Ray Box
{903}{}{대통령 리차드슨}           # qhPrzRch.int    ; Enclave President Richardson talking head.
{904}{}{곡사포}                       # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{문}                           # WIEntDor.int    ; Entrance to Sierra Base Door
{906}{}{새끼 데스클로}                 # OCBabDth.int    ; Baby Deathclaws in Vault 13
{907}{}{위험한 댄}                  # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{의사 존슨}                    # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{보안관 마리온}                 # RCMarion.int    ; Sheriff Earl Marion
{910}{}{에스코티 시장}                  # RCAscort.int    ; Mayor Ascorti of Redding
{911}{}{노딩}                        # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{벨라니}                         # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{펀다운}                       # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{드래곤}                     # FCDragon.int    ; The Dragon, San Fran
{915}{}{마구간지기}                     # mcSblBoy.int    ; Modoc Stable Boy
{916}{}{상인}                         # mcTrader.int    ; Modoc Trader
{917}{}{마을사람}                    # mcPerson.int    ; Modoc Townspeople
{918}{}{슬래그}                           # mcSlgExt.int    ; Ghost Farm Slag Exit Guard
{919}{}{슬래그}                           # mcSlgGrd.int    ; Ghost Farm Slag Enterance Guard
{920}{}{로 판}                         # FCLoPan.int     ; Lo Pan in San Fran.
{921}{}{배저}                         # FCBadger.int    ; Badger in San Fran.
{922}{}{조쉬}                           # RCJosh.int      ; Josh Laurance of Redding
{923}{}{캐미네토}                      # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{베티}                          # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{무기상}                  # FCGunmer.int    ; San Fran's gun Merchant
{926}{}{문}                           # ZIWodDor.int    ; Generic Wooden Door
{927}{}{문}                           # ZIMtlDor.int    ; Generic Metal Door
{928}{}{발생기}                        # SSEmtN2.int     ; Emitter in NCR area 2
{929}{}{쥐 신}                        # ZCRatGod.int    ; Rat God in Klamath
{930}{}{}                               # ECBox.int       ; Random box that has stuff in it.
{931}{}{카가}                           # ECKaga1.int     ; Random Encounter Kaga 1
{932}{}{카가}                           # ECKaga2.int     ; Random Encounter Kaga 2
{933}{}{카가}                           # ECKaga3.int     ; Random Encounter Kaga 3
{934}{}{카가}                           # ECKaga4.int     ; Random Encounter Kaga 4
{935}{}{카가}                           # ECKaga5.int     ; Random Encounter Kaga 5
{936}{}{현상금 사냥꾼}                  # ECBHunter.int   ; Random Encounter Bounty Hunter
{937}{}{컴퓨터}                       # VIMedCom.int    ; Vault City Medical Computer
{938}{}{컴퓨터}                       # VICenCom.int    ; Vault City Central Computer
{939}{}{컴퓨터}                       # VIAloCom.int    ; Vault City Allocation Computer
{940}{}{대로우}                         # VCDarrow.int    ; Vault City Sub-Amenities Officer Darrow
{941}{}{파렐}                        # VCFarrel.int    ; Vault City Sub-Amenities Officer Farrell
{942}{}{바 손님}                     # VCBarPat.int    ; Vault City Bar Patron
{943}{}{볼트 시민}                  # VCWrkCit.int    ; Vault City Working Citizen
{944}{}{볼트 수행원}                  # VCSlave.int     ; Vault City Slave
{945}{}{환기용 수직갱도}              # VIShft2b.int    ; Vault City Ventilation Shaft 2B
{946}{}{찰리}                        # VCCharli.int    ; Vault City Puking Charlie
{947}{}{냉각수 제어반}          # GSValve.int     ; Gecko Coolant Control Panel
{948}{}{응가}                            # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{949}{}{그랜트}                          # scWesGrd.int    ; Westin's Force Field Guard
{950}{}{발생기}                        # SSEmiWes.int    ; Westin's Force Field Emitter
{951}{}{발생기}                        # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{컴퓨터 단말기}              # SICmpWes.int    ; Westin's computer terminal for the field.
{953}{}{황제 단말기 v8.8}          # FSEmpTer.int    ; Computer Terminal in San Fran
{954}{}{버드 부통령}            # QCBird.int      ; Enclave, Vice President Bird
{955}{}{마틴}                         # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{켄 리}                        # FCKenLee.int    ; Ken Lee in San Francisco
{957}{}{그래니트 병장}                   # QCGranit.int    ; Sgt. Granite of the Enclave Patrol
{958}{}{프랭크 호리건}                 # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{맵 스크립트}                     # GeckJunk.int    ; Map Script for Gecko Junkyard
{960}{}{맵 스크립트}                     # GeckTunl.int    ; Map Script for Gecko Tunnels
{961}{}{문}                           # SSFrgDor.int    ; Fergus's Door script
{962}{}{문}                           # SSGunDor.int    ; Gunther's Door script to Tandi
{963}{}{문}                           # SSFlxDor.int    ; Felix's Door script
{964}{}{밧줄}                           # SSRope.int      ; Rope.. for you to climb
{965}{}{발생기}                        # SSEmiEnt.int    ; Emitter in Ncr Entrance
{966}{}{컬링 박사}                    # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{게시판}                 # SSSign.int      ; Sign in NCR Entrance
{968}{}{두더지쥐}                       # mcMolRat.int    ; Ghost Farm Mole Rat
{969}{}{대통령 비서}          # QCPrsSec.int    ; President's personal intern (uh sectertary)
{970}{}{톰 머레이}                     # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{견고한 문}                    # SSCrpDor.int    ; Craps table door in NCR
{972}{}{마을사람}                    # mcPeasan.int    ; Modoc Peasant, they attack the farm
{973}{}{볼트 시티 의회 구역}        # VCtyCocl.int    ; Map Script Vault City Council Area
{974}{}{공기 정화기}                   # HSPurify.int    ; Air Purifier for Broken Hills
{975}{}{바위}                          # esEntRks.int    ; Military Base Entrance Rocks
{976}{}{도박꾼}                        # RCGamble.int    ; Redding Generic Gamblers
{977}{}{공간 스크립트}                 # HtCorpse.int    ; Spatial Script for Corpses
{978}{}{SCCheat}                        # SCCheat.int     ; Cheat Character for NCR
{979}{}{죄수}                       # QCGenPrs.int    ; Enclave Generic Prisoner
{980}{}{시민}                        # QCGenCit.int    ; Enclave Generic Citizens
{981}{}{경비}                          # QCGenGrd.int    ; Enclave Generic Guards
{982}{}{과학자}                      # QCGenSci.int    ; Enclave Generic Scientist
{983}{}{단말기}                       # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                               # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                               # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{발생기}                        # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{방폭문}                     # QIBstDr1.int    ; Blast Door for Reactor Off to remain closed
{988}{}{방폭문}                     # QIBstDr2.int    ; Blast Door for Reactor On to remain closed
{989}{}{대로우의 재고품}                 # VIDarBox.int    ; Vault City Darrow Shop Inventory
{990}{}{문}                           # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{슈퍼 두퍼 뮤턴트}             # ecTlkMut.int    ; Military Base Conversation Mutants
{992}{}{화학자}             # fcChemst.int    ; Chemist in San Francisco
{993}{}{그룬델}                        # ecGrunde.int    ; Military Base Mouse Hunter
{994}{}{멜콰이어 주니어}                   # ecMelKid.int    ; Some Town USA, Melchior's Kid
{995}{}{망막 스캐너}                # WIRetScn.int    ; Retinal Scanner in the Sieera Base
{996}{}{승강기 문}                  # WIElvDor.int    ; Elevator Door in the Seirra Base
{997}{}{인공두뇌 로봇}          # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{벽}                           # WIScrtDr.int    ; Sierra Base Secert Door
{999}{}{맵 스크립트}                     # broken2.int     ; Map Script for Broken Hills Map 2
{1000}{}{파렐의 재고품}               # VIFarBox.int    ; Vault City Farrell Shop Inventory
{1001}{}{해리의 재고품}                 # VIHarBox.int    ; Vault City Harry Shop Inventory
{1002}{}{상자}                           # VICtyBox.int    ; Vault City Courtyard Temp Inventory Box
{1003}{}{상자}                           # VIDwtBox.int    ; Vault City Downtown Temp Inventory Box
{1004}{}{데렉}                         # dcDerek.int     ; Derek in the Den
{1005}{}{터비의 친구}                # dcTubFri.int    ; Tubby's Junkie Friends in the Den
{1006}{}{도박꾼}                       # dcGamble.int    ; Gamblers in the Den
{1007}{}{노예}                         # dcSlave.int     ; Pen Slaves in the Den
{1008}{}{경비}                         # dcMetRom.int    ; Metzger Room Guard in the Den
{1009}{}{노예상인}                        # dcPenGrd.int    ; Slaver Pen Guard in the Den
{1010}{}{라라}                          # dcLara.int      ; Lara in the Den
{1011}{}{타일러}                         # dcTyler.int     ; Tyler in the Den
{1012}{}{마크}                          # dcMarc.int      ; Marc in the Den
{1013}{}{게시판}                # diBulBrd.int    ; Bulletin Board in the Den
{1014}{}{노예상인}                        # dcVicGrd.int    ; Vic Guard in the Den
{1015}{}{노예상인}                        # dcSlvGrt.int    ; Slaver Greeter in the Den
{1016}{}{프레드}                          # dcFred.int      ; Fred in the Den
{1017}{}{상자}                           # diFliBox.int    ; Flick Box in the Den
{1018}{}{상자}                           # diMomBox.int    ; Mom Box in the Den
{1019}{}{상자}                           # diSmiBox.int    ; Smitty Box in the Den
{1020}{}{자동차 트렁크}                     # ZICrTrnk.int    ; generic script for Car Trunk
{1021}{}{보안 문}                 # QIPzlDor.int    ; Door for the puzzle room in the Enclave
{1022}{}{컴퓨터 단말기}             # FSPhySta.int    ; Physics computer station in San Fran
{1023}{}{컴퓨터 단말기}             # FSBioSta.int    ; Biology computer station in San Fran
{1024}{}{컴퓨터 단말기}             # FSCheSta.int    ; Chemistry computer station in San Fran
{1025}{}{라오 초우}                      # FCLaoCho.int    ; Merchant in San Fran
{1026}{}{}                              # FIPaper.int     ; Scrap Papers that combine into password note. Should only be put on one of the pieces.
{1027}{}{환기용 수직갱도}             # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{맵 스크립트}                    # EncTrp.int      ; Map Script for Enclave Trap Rooms
{1029}{}{시체}                     # HtBody.int      ; Script for dead bodies in Broken Hills
{1030}{}{노출된 선}                 # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{상자}                           # diMetBox.int    ; Metzger Box from Slave Crap
{1032}{}{노예}                         # dcRunSlv.int    ; Den Slave Run Fleeing Slaves
{1033}{}{노예}                         # dcAtkSlv.int    ; Den Slave Run Hostile Slaves
{1034}{}{노예상인}                        # dcRnSlvr.int    ; Den Slave Run Slavers
{1035}{}{Chip}                          # FCChip.int      ; Chip in San Fran no spleen
{1036}{}{원자로}                       # QIReactr.int    ; Reactor in the Enclave
{1037}{}{원자로 컴퓨터}              # QIRctrCm.int    ; Reactor Computer in the Enclave
{1038}{}{출납원}                   # RCCshTnd.int    ; Redding Cash Tender in the Casino
{1039}{}{금전출납기}                      # RICshBox        ; Cash Box for the Cash Tender
{1040}{}{와나밍고}                     # RCWanami.int    ; Wanamingo
{1041}{}{바 손님}                    # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{바 손님}                    # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{감옥 문}                     # RIJalDor.int    ; Jail Door in Redding
{1044}{}{슈즈}                          # FCSuze.int      ; Suze in San Fran
{1045}{}{선장 론 마이어스}            # FCRonMey.int    ; Captain Ron Meyers
{1046}{}{우리 문}                      # diPenDor.int    ; Slave Pen Door in the Den
{1047}{}{와나밍고 광산}                # RedWan1.int     ; Map Script for Wanamingo Mine
{1048}{}{와나밍고 광산 출입구}       # RedWane.int     ; Map Script for Wanamingo Mine Entrance
{1049}{}{프로그 모턴}                   # RCFrog.int      ; Frog Morton
{1050}{}{데이브 H.}                       # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{문}                          # diVicDor.int    ; Vic's Room Door in the Den
{1052}{}{문}                          # diRomDor.int    ; Metzger's Room Door in the Den
{1053}{}{구역질하는 찰리}                # vccharly.int    ; Puking Charlie in Vault Courtyard
{1054}{}{Painting}                      # SIPaint.int     ; Revales Vault 13 on examination.
{1055}{}{맵 스크립트}                    # SFChina.int     ; San Fran China Map
{1056}{}{바텐더}                     # VCCouBar.int    ; Vault City Council Area Bartender
{1057}{}{상자}                           # VIBarBox.int    ; Vault City Slave Sale Inventory Dump
{1058}{}{오토-닥}                      # VIAutDoc.int    ; Vault City Courtyard Auto-Doc
{1059}{}{}                              # RIMinEnt.int    ; Entrance Back to the Mines
{1060}{}{광산 터널}                 # RedMTun.int     ; Map Script for Mining Tunnel
{1061}{}{로봇}                         # KCRob.int       ; Robot on Klamath Canyon
{1062}{}{}                              # FiGunTbl.int    ; Gun Merchant table in San fran
{1063}{}{맵 스크립트}                    # KlaMall.int     ; Map Script for Klamath Mall area
{1064}{}{맵 스크립트}                    # KlaTrap.int     ; Map Script for Klamath Still area
{1065}{}{리디아}                         # VCDwnBar.int    ; Vault City Downtown Bartender
{1066}{}{}                              # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{로켓맨}           # FCRocMan.int    ; Rocket man in San Fran
{1068}{}{AHS-7}                         # FCOz7.int       ; Oz 7 in San Fran
{1069}{}{크로켓}                      # FCCrocke.int    ; Crockett in San Fran
{1070}{}{아만다}                        # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{조슈아}                        # VCJoshua.int    ; Vault City Courtyard Joshua, Slave
{1072}{}{발레리}                       # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{교육 시스템}               # VITeach.int     ; Vault City Teaching System
{1074}{}{상자}                         # diCrate.int     ; Den Crate in Church
{1075}{}{오줌싸는 남자}                    # VCUrine.int     ; Peeing Guy in Vault City Council Area
{1076}{}{커티스}                        # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{마크}                          # FCMarc.int      ; Marc, Punk in San Fran
{1078}{}{컴퓨터}                      # FSElComp.int    ; Hubologists computer
{1079}{}{AHS-9}                         # FCOz9.int       ; Hubologist main dude
{1080}{}{경비}                         # FCElGrd.int     ; Hubologist's guards
{1081}{}{돌무더기}                 # VIRocks.int     ; Pile of Rocks w/ Hidden Wrench
{1082}{}{문}                          # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{경비}                         # dcRebGrd.int    ; Den Rebecca Guard
{1084}{}{경비}                         # dcRebDor.int    ; Den Rebecca Door Guard
{1085}{}{문}                          # diRebDor.int    ; Den Rebecca Door
{1086}{}{현상 수배서}                   # ZSWsign.int     ; Generic Wanted Sign
{1087}{}{웡 박사}                      # FCDrWong.int    ; Dr. Wong in San Fran area
{1088}{}{탁자}                         # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{문}                          # WILv1Dor.int    ; Locked Door on Level 1 Entrance         # local_vars=8
{1090}{}{펑크족}                          # FCFemPnk.int    ; San Fran Female punk
{1091}{}{펑크족}                          # FCMalPnk.int    ; San Fran Male Punk
{1092}{}{라이언}                          # FCRyan.int      ; San Fran Punk Ryan
{1093}{}{상자}                           # HIBh1Box.int    ; Broken Hills Temp Inventory Box
{1094}{}{}                              # FCJuavki.int    ; Juan and Vikkin in San Fran Elron Camp
{1095}{}{맨홀}                       # HIManHol.int    ; Manhole to Basement in Liz's Store
{1096}{}{맵 스크립트}                    # SFElronb.int    ; Elron Base map Script
{1097}{}{사다리}                        # HILadder.int    ; Ladder up to Liz's Store
{1098}{}{샌드백}                  # WIPnchBg.int    ; Punching Bag in the Sierra Depot
{1099}{}{문}                          # WIBayDor.int    ; Sierra Base Repair Bay Door
{1100}{}{알람}                         # GSAlarm.int     ; Gecko Reactor alarm
{1101}{}{바닥 판}                   # WIPlTrp2.int    ; Plasma Floor Trap Level 2 of Seirra
{1102}{}{바닥 판}                   # WIPlTrp3.int    ; Plasma Floor Trap Level 2 of Seirra
{1103}{}{바닥 판}                   # WIPlTrp4.int    ; Plasma Floor Trap Level 2 of Seirra
{1104}{}{바닥 판}                   # WIPlTrp5.int    ; Plasma Floor Trap Level 2 of Seirra
{1105}{}{바닥 판}                   # WIPlTrp6.int    ; Plasma Floor Trap Level 2 of Seirra
{1106}{}{바닥 판}                   # WIPlTrp7.int    ; Plasma Floor Trap Level 2 of Seirra
{1107}{}{바닥 판}                   # WIPlTrp8.int    ; Plasma Floor Trap Level 2 of Seirra
{1108}{}{바닥 판}                   # WIPlTrp9.int    ; Plasma Floor Trap Level 2 of Seirra
{1109}{}{바닥 판}                   # WIPlTrpA.int    ; Plasma Floor Trap Level 2 of Seirra
{1110}{}{바닥 판}                   # WIPlTrpB.int    ; Plasma Floor Trap Level 2 of Seirra
{1111}{}{바닥 판}                   # WIPlTrpC.int    ; Plasma Floor Trap Level 2 of Seirra
{1112}{}{바닥 판}                   # WIPlTrpD.int    ; Plasma Floor Trap Level 2 of Seirra
{1113}{}{바닥 판}                   # WIPlTrpE.int    ; Plasma Floor Trap Level 2 of Seirra
{1114}{}{바닥 판}                   # WIPlTrpF.int    ; Plasma Floor Trap Level 2 of Seirra
{1115}{}{발생기}                       # WSEmit4a.int    ; Emitter, Level 4 in Sierra Base
{1116}{}{발생기}                       # WSEmit4b.int    ; Emitter, Level 4 in Sierra Base
{1117}{}{발생기}                       # WSEmit4c.int    ; Emitter, Level 4 in Sierra Base
{1118}{}{역장}                   # WSFeld4a.int    ; Force Field, Level 4 in Sierra Base
{1119}{}{역장}                   # WSFeld4b.int    ; Force Field, Level 4 in Sierra Base
{1120}{}{역장}                   # WSFeld4c.int    ; Force Field, Level 4 in Sierra Base
{1121}{}{허볼로지스트}                    # FCElrInd.int    ; Elron Indoctrinee
{1122}{}{컴퓨터}                      # FStnkCmp.int    ; Posiden Tanker Computer
{1123}{}{방공호 문}                   # WIBnkDor.int    ; Bunker Door for the Sierra Depot
{1124}{}{입구}                          # miGate.int      ; Modoc Gate
{1125}{}{상자}                           # WITrpBx1.int    ; Sierra Base Trapped Box
{1126}{}{모턴 형제}                # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{발생기}                       # FSEmt1.int      ; Force Field emitter 1 in San Fran
{1128}{}{발생기}                       # FSEmt2.int      ; Force Field emitter 2 in San Fran
{1129}{}{발생기}                       # FSEmt3.int      ; Force Field emitter 3 in San Fran
{1130}{}{맵 스크립트}                    # Cave6.int       ; Fake Vault 13 Cave map
{1131}{}{체트}                          # VCChet.int      ; Illicit Allocations Officer Chet
{1132}{}{맵 스크립트}                    # NewRVB.int      ; New Reno Helicopter Script Map
{1133}{}{버티버드}                     # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{살바토레 경비}               # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{살바토레 경비}               # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{군인}                      # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{군인}                      # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{상자}                         # niHSCrat.int    ; New Reno Helicopter Script Crate
{1139}{}{Mr. 핸디}                     # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{살바토레 경비}               # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guard
{1141}{}{공간 스크립트}                # ntHSGrd.int     ; New Reno Helicopter Script Guarding Spacial
{1142}{}{문}                          # niEldDor.int    ; New Reno Elderidge Door
{1143}{}{문}                          # niSalDor.int    ; New Reno Salvatore Door
{1144}{}{문}                          # niMyrDor.int    ; New Reno Myron Door
{1145}{}{}                              # FcMonst.int     ; Monster in the PMS Tanker
{1146}{}{맵 스크립트}                    # SFTanker.int    ; San Fran Tanker map
{1147}{}{노예}                         # VCSlav2.int     ; Vault City Prisoner Slaves
{1148}{}{볼트 시민}                 # VCBarCit.int    ; Vault City Bar Patron
{1149}{}{문}                          # niBasDor.int    ; New Reno Locking Doors
{1150}{}{권투선수}                         # ncFightr.int    ; New Reno Boxer Actually Fighting
{1151}{}{볼트 문}                    # RIVltDor.int    ; Locked Vault Door in Redding
{1152}{}{잔}                          # CcXarn.int      ; Xarn in Navarro
{1153}{}{라울}                          # CcRaul.int      ; Raul in Navarro
{1154}{}{퀸시}                        # CcQuincy.int    ; Quincy in Navarro
{1155}{}{병참장교}                 # CcQmstr.int     ; Quartermaster in Navarro
{1156}{}{경비}                         # CcMedGrd.int    ; Med Lab Guard in Navarro
{1157}{}{K-9}                           # CcK9.int        ; K9 in Navarro
{1158}{}{박사}               # CcDoctor.int    ; Dr Shreber in Navarro
{1159}{}{기술자}                    # CcATech.int     ; Air Tech in Navarro
{1160}{}{기술자}                    # CcACon.int      ; Air Control in Navarro
{1161}{}{경비}                         # CcDrGrd.int     ; Door Guard in Navarro
{1162}{}{경비}                         # Ccggbak.int     ; Gate Guard Backup in Navarro
{1163}{}{경비}                         # CcGrdca.int     ; Guard (combat armor) in Navarro
{1164}{}{경비}                         # CcGrdpa.int     ; Guard (power armor) in Navarro
{1165}{}{기술자}                    # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{기술자}                    # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{기술자}                    # CcComp1.int     ; Computer Tech1 in Navarro
{1168}{}{기술자}                    # CcComp2.int     ; Computer Tech2 in Navarro
{1169}{}{낙반}                       # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{엔클레이브 순찰대}             # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{방폭문}                    # QIEndDor.int    ; Doors at the End Fight Area
{1172}{}{맵 스크립트}                    # EncDet.int      ; Map Script for Enclave Detention Center
{1173}{}{맵 스크립트}                    # EncDock.int     ; Map Script for Enclave Dock
{1174}{}{맵 스크립트}                    # EncGd.int       ; Map Script for Enclave Guard Barracks
{1175}{}{맵 스크립트}                    # EncPres.int     ; Map Script for Enclave Presidential Area
{1176}{}{맵 스크립트}                    # EncRetr.int     ; Map Script for Enclave Reactor Area
{1177}{}{맵 스크립트}                    # EncFite.int     ; Map Script for Enclave Fight Area
{1178}{}{보안 로봇}                # QCSecBot.int    ; Enclave Security Robot
{1179}{}{헌금함}                      # niTulBox.int    ; New Reno Poor Box
{1180}{}{시체}                          # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{상자}                           # HiJacBox.int    ; Broken Hills Jacob inventory box
{1182}{}{상자}                           # HiDocBox.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{상자}                           # HiOutBox.int    ; Broken Hills Outfitter inventory box
{1184}{}{행상 경비}                 # RCCvnGrd.int    ; Generic Caravan Guard
{1185}{}{행상 기사}                # RCCvnDrv.int    ; Generic Caravan Driver
{1186}{}{링 아나운서}                # ncAnounc.int    ; New Reno Boxing Announcer
{1187}{}{라운드 걸}                     # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{권투선수}                         # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{문}                          # VIVltDr2.int    ; Vault Doors in Vault 8
{1190}{}{치트 캐릭터}               # ncCheat.int     ; New Reno Cheat Character
{1191}{}{홀로디스크}                      # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{홀로디스크}                      # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{홀로디스크}                      # FIElrDsk.int    ; Hubologist Holodisk
{1194}{}{쪽지}                          # HINote.int      ; Script for Francis/Zaius Note
{1195}{}{도그밋}                       # ECDogMet.int    ; Dog Meat from Special random encounter
{1196}{}{캣츠 포우 잡지 #5}         # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{레이더스 지도}                   # niRaiMap.int    ; New Reno Raiders Map in Bishop's Safe
{1198}{}{유기견}                    # ECPariah.int    ; Pariah Dog in Low Luck encounter
{1199}{}{경적}                        # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{광산}                          # IIMine.int      ; Mines in Raiders Cave
{1201}{}{구덩이}                           # IIPit.int       ; Pits in the Raiders Cave
{1202}{}{유조선 무역상}		                        # FCTnkGmr.int    ; Tanker Gun Merchant San Fran
{1203}{}{유조선 바텐더}		                      # FCTnkBar.int    ; Tanker Bar Tender
{1204}{}{유조선 무역상}		                      # FCTnkMer.int    ; Tanker Merchant
{1205}{}{}                              # FITGunTb.int    ; Tanker Gun Mer's table
{1206}{}{}                              # FITMerTb.int    ; Tanker Merchant's Table
{1207}{}{발생기}                       # FSPemtr1.int    ; Palace Emitter 1
{1208}{}{발생기}                       # FSPemtr2.int    ; Palace Emitter 2
{1209}{}{발생기}                       # FSPemtr3.int    ; Palace Emitter 3
{1210}{}{발생기}                       # FSEmpEmt.int    ; Emporor Computer's Force Field
{1211}{}{폴아웃 2 힌트북}            # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                              # csTouch.int     ; Script to signal if dude touches container objects (in Navarro)
{1213}{}{}                              # csArea.int      ; Script to signal if dude enters an area (in Navarro)
{1214}{}{경비}                         # RCAscGrd.int    ; Generic Guard for Ascorti's Bar
{1215}{}{탐사자}                    # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{주류 밀수업자}                   # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                              # csOpen.int      ; Script to signal if dude uses door w/o permission (in Navarro)
{1218}{}{댄}                           # hcDan.int       ; Dan, Spouse of murdered conspirator.
{1219}{}{형편없는 코미디언}               # ncComedi.int    ; New Reno Comedian
{1220}{}{쓰레기통 가수}               # ncBand.int      ; New Reno Trashcan Band
{1221}{}{맵 스크립트}                    # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                              # csGate.int      ; Script to signal if dude uses gate w/o permision (in Navarro)
{1223}{}{무덤}                         # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{커핀 윌리}                 # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{무선 잠금장치 컴퓨터}        # FSFobTer.int    ; Fob Terminal
{1226}{}{무선 잠금장치 문}            # FSFobDor.int    ; Fob Door
{1227}{}{컴퓨터}                      # ccNComp.int     ; Navarro Computer
{1228}{}{콜}                          # vcKohl.int      ; Vault City Info Officer Kohl
{1229}{}{아이}                         # ECChild.int     ; Random Encounter Children
{1230}{}{요리사}                        # ccCook.int      ; Navarro Cook
{1231}{}{포탑}                        # ccTurret.int    ; Navarro Turret
{1232}{}{브라이언}                         # hcBrian.int     ; Brian, the Power Technician
{1233}{}{발전기}                     # hiPower.int     ; Power Generator for Broken Hills
{1234}{}{제어반}                       # hiConsole.int   ; Power Station Console in Broken Hills
{1235}{}{거대 개미}                     # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{거대 개미}                     # hcAnt2.int      ; Broken Hills Ant - Missing Person Quest
{1237}{}{문}                          # csXDoor.int     ; Another lousy door script -signals xarn to leave
{1238}{}{}                              # htSecret.int    ; Spatial for secret area of Broken Hills Mine
{1239}{}{상자}                           # niEthBox.int    ; New Reno Ethyl Wright Shop Box
{1240}{}{에릭}                          # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                              # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{상자}                           # viRanBox.int    ; Randal's Stock Box in Vault City
{1243}{}{거대 전갈}                # iiScorp.int     ; Raiders Scorpions 2X poison
{1244}{}{제인}                          # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                              # VTAloMrk.int    ; Spatial Script for Allocation Computer VCity
{1246}{}{맵 스크립트}                    # Cave7.int       ; Fake Vault 13 map
{1247}{}{진피 핍보이}                # niDermal.int    ; New Reno Dermal Pip-Boy
{1248}{}{푸치}                         # ncEldDog.int    ; New Reno Eldridge Dogs
{1249}{}{래트래이}                       # RCRatray.int    ; Rattray, Doc Johnson's assistant
{1250}{}{배우자}                        # HCHusWif.int    ; Mutant Husband/Wife Broken Hills
{1251}{}{로판 경비}                   # FCLoGrd.int     ; LoPan Guard in San Fran
{1252}{}{맵 스크립트}                    # Navarro.int     ; Map script for Navarro
{1253}{}{문}                          # VIVltDr3.int    ; Vault Door in Vault 8 - Martin
{1254}{}{인공두뇌 개}                # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{루크}                          # FCNLuke.int     ; Luke in NCR
{1256}{}{조슈아}                        # FCDJosh.int     ; Joshua BOS in the Den
{1257}{}{입구}                          # iiLockDr.int    ; Gates in Raiders area
{1258}{}{맷}                          # FCFmatt.int     ; Matt in San Fran BOS
{1259}{}{문}                          # FSBroDor.int    ; Brotherhood Door
{1260}{}{경비}                         # hcGrd2.int      ; Bank Guard 2 in Broken Hills
{1261}{}{문}                          # QIGeckDr.int    ; Door Requiring the player to use the geck
{1262}{}{컴퓨터}                      # FSFace.int      ; Ace Computer system in San Fran
{1263}{}{단말기}                      # QITurTrm.int    ; Generic Enclave Turret Terminal
{1264}{}{포탑}                        # QCTurret.int    ; Enclave Turrets
{1265}{}{척 스토저스}                # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                              # htChuck.int     ; Spatial Script for waking up Chuck
{1267}{}{단말기}                      # viTerm.int      ; Vault City Vault Terminal
{1268}{}{폭력단원}                     # RCMotGng.int    ; Frog Morton's gang
{1269}{}{치터}                       # ccCheat.int     ; Cheat character in Navarro
{1270}{}{}                              # FSTnkrdr.int    ; Tanker Doors in San Fran
{1271}{}{소농민}                       # OCPeaon.int     ; NCR peaons
{1272}{}{라벤더 꽃}           # diRebBok.int    ; Den Becky's Book
{1273}{}{방사능전갈}                   # hcScorp.int     ; Broken Hills Scorpion
{1274}{}{교수}                     # hcProf.int      ; Broken Hills Professor
{1275}{}{상자}                           # hiPrfBx1.int    ; Professor's Box in Broken Hills
{1276}{}{상자}                           # hiPrfBx2.int    ; Professor's Box in Broken Hills
{1277}{}{시모어}                       # hcSeymore.int   ; Seymour the talking Plant/Broken Hills
{1278}{}{존 설리반}                 # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{럼피}                         # hcLumpy.int     ; Lumpy the car accident victim - Broken Hills
{1280}{}{}                              # BISpyHol.int    ; Spy Holodisk for NCR
{1281}{}{}                              # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                              # SIWesHol.int    ; Westin Holodisk
{1283}{}{경비}                         # SCBGrd.int      ; Buster's Guard
{1284}{}{}                              # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                              # SIGcaObj.int    ; NCR Guard Captain notify obj
{1286}{}{티폰}                        # hcTyphon.int    ; Typhon, Son of Set - Broken Hills
{1287}{}{경호원}                     # ECBdyGrd.int    ; BodyGuard in Vignette
{1288}{}{맵 스크립트}                    # GamMovie.int    ; Game Movie map
{1289}{}{락커}                        # ziLocker.int    ; Generic Locker Script
{1290}{}{우물}                          # hiWell.int      ; Broken Hills Well
{1291}{}{미키}                         # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{포탑}                        # WCTurret.int    ; Turret for Sierra Depot
{1293}{}{늙은 구울}                     # hcOldGhl.int    ; Ghouls in Old-Folks Home - Broken Hills
{1294}{}{심복}                      # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{엘모}                          # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{화장실}                        # niToilet.int    ; Toilet - Contains Grenades - New Reno
{1297}{}{십자가}                         # niCross.int     ; Cross - Golgotha - Buried Cash
{1298}{}{쟁기}                          # viPlow1.int     ; Plow - Vault City
{1299}{}{쟁기}                          # viPlow2.int     ; Plow - Vault City
{1300}{}{전갈}                      # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{발전기}                     # kcGnratr.int    ; Generator player repairs in toxic caves
{1302}{}{문}                          # kcLvatr.int     ; Elevator door in toxic caves
{1303}{}{문}                          # SIVDor.int      ; Vortis Slave Door
{1304}{}{의학 핍 보이}               # niMedica.int    ; New Reno "Doctor Skill" Upgrade
{1305}{}{락커}                        # niPrstLk.int    ; New Reno Prostitute"Locker"
{1306}{}{락커}                        # niBigJLk.int    ; New Reno Big Jesus "Locker"
{1307}{}{락커}                        # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Locker"
{1308}{}{락커}                        # niBoxrLk.int    ; New Reno Boxer "Locker"
{1309}{}{락커}                        # niBis1Lk.int    ; New Reno Bishop Family OK "Locker"
{1310}{}{락커}                        # niPornLk.int    ; New Reno Porn Actress "Locker"
{1311}{}{락커}                        # niBtchLk.int    ; New Reno Bitch "Locker"
{1312}{}{락커}                        # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Locker"
{1313}{}{락커}                        # niEldrLk.int    ; New Reno Eldridge "Locker"
{1314}{}{락커}                        # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Locker"
{1315}{}{락커}                        # niOWriLk.int    ; New Reno Orville Wright "Locker"
{1316}{}{락커}                        # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Locker"
{1317}{}{락커}                        # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Locker"
{1318}{}{락커}                        # niMyGdLk.int    ; New Reno Myron Guard "Locker"
{1319}{}{락커}                        # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Locker"
{1320}{}{락커}                        # niMyrnLk.int    ; New Reno Myron "Locker"
{1321}{}{락커}                        # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Locker"
{1322}{}{락커}                        # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Locker"
{1323}{}{락커}                        # niTryLk.int     ; New Reno Tray "Locker"
{1324}{}{락커}                        # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{맵 스크립트}                    # rndtoxic.int    ; Random Toxic Map
{1326}{}{넌 날 볼 수 없어}              # ecirrad.int     ; critter that irradates
{1327}{}{양철 나무꾼}                  # ecTinWod.int    ; Tin Woodsman
{1328}{}{맵 스크립트}                    # rndTinWd.int    ; Tin Woodsman Map Script
{1329}{}{바위 구조물}               # ecGrdFrv.int    ; Guardian of Forever
{1330}{}{}                              # rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1331}{}{단말기}                      # ecGrdTrm.int    ; Guardian of Forever Water Chip Terminal
{1332}{}{락커}                        # niEld2Lk.int    ; New Reno Eldridge "Locker" HARD LOCK
{1333}{}{}                              # SiRagobj.int    ; Uhh box that Rondo cares
{1334}{}{맵 스크립트}                    # SFCHINA2.int    ; China 2 map
{1335}{}{보안 로봇}                  # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{보안 로봇}                  # KCWupass.int    ; Klamath Guard Robot under Toxic Caves
{1337}{}{락커}                        # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{락커}                        # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{락커}                        # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{락커}                        # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{락커}                        # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{락커}                        # viCGWch1.int    ; VCty - Prison Door Watch Script
{1343}{}{락커}                        # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{락커}                        # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{락커}                        # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{락커}                        # viStkWch.int    ; VCty - Stark Watch Script
{1347}{}{락커}                        # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{락커}                        # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{락커}                        # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{락커}                        # viWalWch.int    ; VCty - Wallace Watch Script
{1351}{}{락커}                        # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{락커}                        # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{락커}                        # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{락커}                        # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{락커}                        # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{락커}                        # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{항만 무단 거주자}                 # FCDocSqa.int    ; San Fran - Doc Squatter
{1358}{}{항만 꼬마}                      # FCDocKid.int    ; San Fran - Doc Kids
{1359}{}{맵 스크립트}                    # RndWhale.int    ; Random Whale Script
{1360}{}{퍼시 크럼프}                   # gcPercy.int     ; Percy Crump, Gecko Merchant
{1361}{}{상자}                           # giPerBox.int    ; Percy's Stock Box
{1362}{}{상자}                           # giJnkBox.int    ; Gecko Junkyard Temp Inventory Box
{1363}{}{문}                          # niWriDor.int    ; New Reno Wright Room Door
{1364}{}{위대한 아나니아}             # dcAnan.int      ; The Great Ananias, Mummy Master
{1365}{}{맵 스크립트}                    # RndUVilg.int    ; Unwashed Villager map
{1366}{}{언워시드 빌리저}             # ECWash.int      ; Unwashed Villagers... Ug You figure out where they go.
{1367}{}{악플러}                       # ECSpammr.int    ; Spammer in Unwashed Encounter
{1368}{}{Map}                           # eiSanMap.int    ; Military Base San Francisco Map
{1369}{}{맵 스크립트}                    # RndShutl.int    ; Random Shuttle Map
{1370}{}{맵 스크립트}                    # rndParih.int    ; Random Pariah Map Script
{1371}{}{맵 스크립트}                    # rndBHead.int    ; Random Big Head map
{1372}{}{맵 스크립트}                    # rndcafe.int     ; Random Cafe Map
{1373}{}{누카-콜라 자판기}             # ZINuke.int      ; Nuka-Cola Machine
{1374}{}{Dock}                          # sfdock.int      ; map script for San Fran Dock
{1375}{}{문}                          # ciCrisDr.int    ; Chris's Door
{1376}{}{지뢰}                     # rtlndmin.int    ; Redding Land Mines
{1377}{}{지뢰}                     # wtlndmin.int    ; Sierra Depot Land Mines
{1378}{}{당신의 전}                       # ncExSpou.int    ; New Reno Ex-Spouse script
{1379}{}{멜}                           # ECMel.int       ; Mel that Dogmeat Creates.
{1380}{}{통풍구}                          # ciVent.int      ; Vent into Navarro
{1381}{}{케빈}                         # ccKevin.int     ; Kevin in Navarro
{1382}{}{알람}                         # csAlarm.int     ; Navarro base on alert lights
{1383}{}{락커}                        # ciQunWch.int    ; Quincy Locker watch script
{1384}{}{락커}                        # ciRulWch.int    ; Raul Locker Watch Script
{1385}{}{락커}                        # ciCmdWch.int    ; Commanded Locker Watch Script
{1386}{}{}                              # SSSign.int      ; NCR Statue
{1387}{}{}                              # ctFob.int       ; Fob EXP Spatial Script
{1388}{}{}                              # ctPlans.int     ; Vertibird EXP Spatial Script
{1389}{}{}                              # ctK9Part.int    ; K9 Part EXP Spatial Script
{1390}{}{}                              # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                              # csOpen2.int     ; Script to signal if dude uses door w/o permision (in Navarro)
{1392}{}{}                              # ctSound.int     ; Soundproof Room Spatial Script
{1393}{}{}                              # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{주류 밀수업자}                    # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                              # ziWeakLk.int    ; Generic Weak Lock Watch Script
{1396}{}{}                              # ziMedmLk.int    ; Generic Medium Lock Watch Script
{1397}{}{순회 쇼의 꼬마}                     # dcCarnKd.int    ; Carny Kid - The Den
{1398}{}{}                              # ciDocWch.int    ; Raul Locker Watch Script
{1399}{}{}                              # ziHardLk.int    ; Generic Hard Lock Watch Script
{1400}{}{광산}                          # CIMine.int      ; Mines in Raiders Cave
{1401}{}{락커}                        # niBisHLk.int    ; New Reno Bishop Hard Locker
{1402}{}{문}                          # niBisHDr.int    ; New Reno Bishop Hard Locked Door
{1403}{}{}                              # ntRicRom.int    ; New Reno Richard Wright Room Spacial
{1404}{}{}                          # MIMirDor.int    ; Miria's Bedroom Door  
{1405}{}{}                          # MIDavDor.int    ; Davin's Bedroom Door 
{1406}{}{}                          # SIPtbox2.int    ; box where Merk hides your car trunk stuff
{1407}{}{}                          # sfshutl1.int    ; map script to Hubologist entrance (shuttle)
{1408}{}{}                          # abbey.int       ; Abbey map script
{1409}{}{}                          # abbilbox.int    ; bill's storage box
{1410}{}{빌}                      # abbill.int      ; Abbey Bill
{1411}{}{}                          # abbook.int      ; Abbey library book
{1412}{}{아이}                     # abchild.int     ; Abbey child
{1413}{}{데스 클로}                 # abdeathc.int    ; Dave's Door
{1414}{}{일레인 수녀}             # abelaine.int    ; Dave's Door
{1415}{}{무덤}                     # abgrave1.int    ; Dave's Door
{1416}{}{무덤}                     # abgrave2.int    ; Dave's Door
{1417}{}{행크 수사}              # abhank.int      ; Dave's Door
{1418}{}{수도원 의사}              # abhealer.int    ; Dave's Door
{1419}{}{존 수사}              # abjohn.int      ; Dave's Door
{1420}{}{맥스 수사}               # abmax.int       ; Dave's Door
{1421}{}{무역상}                  # abmerch1.int    ; Dave's Door
{1422}{}{무역상}                  # abmerch2.int    ; Dave's Door
{1423}{}{무역상 경비}            # abmergrd.int    ; Dave's Door
{1424}{}{피터슨 부인}             # abmsptsn.int    ; Dave's Door
{1425}{}{수도원 시민}             # abpeople.int    ; Dave's Door
{1426}{}{피터슨 씨}              # abpetson.int    ; Dave's Door
{1427}{}{물 펌프}                # abpump.int      ; Dave's Door
{1428}{}{새뮤얼 수사}            # absamuel.int    ; Dave's Door
{1429}{}{수도원 시민}             # abstand.int     ; Dave's Door
{1430}{}{토마스 수사}            # abthomas.int    ; Dave's Door
{1431}{}{톰}                       # abtom.int       ; Dave's Door
{1432}{}{수도원 컴퓨터}            # acompu.int      ; Dave's Door
{1433}{}{수도원 지도수사}           # ahmonk.int      ; Dave's Door
{1434}{}{수도원 수사}                # amonk1.int      ; Dave's Door
{1435}{}{수도원 수사}                # amonk2.int      ; Dave's Door
{1436}{}{수도원 수사}                # amonk3.int      ; Dave's Door
{1437}{}{수도원 수사}                # amonk4.int      ; Dave's Door
{1438}{}{폴 수사}              # amonk5.int      ; Dave's Door
{1439}{}{부족민}                    # atribal.int     ; Dave's Door
{1440}{}{매튜 수사}           # abmatt.int      ; Abbey Matthew
{1441}{}{map}                           # vill.int      ; Vault Village map script
{1442}{}{두더지쥐}                      # zclvillrat.int      ; Vault Village Monster
{1443}{}{앤}                           # vilann.int      ; Ann in Village
{1444}{}{전사장}                  # tribec1.int     ; script for head warrior
{1445}{}{말리}                         # tribec2.int     ; Script for Marli at well in tribe
{1446}{}{주민}                     # tribec3.int     ; script for random people in tribe
{1447}{}{주술사}                        # tribec4.int     ; script for tribe shaman
{1448}{}{유령}                         # tribec5.int     ; script for ghost in tribe
{1449}{}{부족민}                        # tribec6.int     ; man outside tent for sulik's sister.
{1450}{}{쿠리수}                        # tribec7.int     ; sulik's sister script
{1451}{}{우물}                          # tribei1.int     ; script for well in tribe
{1452}{}{부족 지도}                     # tribem1.int     ; map script for tribe
{1453}{}{부족민}                        # tribec8.int     ; tribal fishermen/women
{1454}{}{세린}                         # tribec9.int     ; Missing Tribal (Serin)
{1455}{}{Tribe map2}                    # tribem2.int     ; Primitive Tribe Map 2
{1456}{}{부족 지도 2 - 공간 1}       # tribesp1.int    ; cave entrance spacial
{1457}{}{부족 지도 2 - 공간 2}       # tribesp2.int    ; cavein spacial
{1458}{}{게코}                         # tribec10.int    ; Gecko in Tribe Cave
{1459}{}{동굴 경비}                    # tribec11.int    ; Tribal guarding entrance to cave
{1460}{}{시체}                     # tribec5a.int    ; Nessa's dead body
{1461}{}{숲 공간}                 # tribesp3.int    ; spacial to trigger seeing the ghost
{1462}{}{돈}                           # slvcc1.int      ; Head of Slaver Camp
{1463}{}{노예상인}                        # slvcc2.int      ; Guards at Slaver Camp
{1464}{}{맵 스크립트}                    # slvcm1.int      ; Map Script to Slaver's Camp
{1465}{}{개}                           # slvcc3.int      ; guard dog on Slaver Map
{1466}{}{노예상인}                        # slvcc5.int      ; Slaver on patrol
{1467}{}{노예}                         # slvcc4.int      ; slaves at Slaver Camp
{1468}{}{노예우리 문}                 # slvco1.int      ; script to locked slavepen door
{1469}{}{선반}                         # hicdshlf.int    ; Chad's Shelf in BH map 2
{1470}{}{문}                          # hichaddr.int    ; Door to Chad's house in BH 2
{1471}{}{꼬마 바비}                  # dclilbby.int      ; Abused boy in Den Residential
{1472}{}{꼬마 바비의 아빠}         # dclbfthr.int    ; Drunken Father of Bobby
{1473}{}{무단 거주자}                      # dcaddct2.int    ; Addicts who live in building which will become the orphanage
{1474}{}{마약상}                   # dcdealer.int    ; Dealer/Body guard in Den Residential
{1475}{}{덴 거주민}                  # dcpeasnt.int    ; Citizen of Den Residential
{1476}{}{고아}                        # dcorphn2.int    ; Orphan living at the Orphanage
{1477}{}{소농민}                       # dcpesnt2.int    ; Peasant 2 of Den Residential
{1478}{}{맵 스크립트}                    # gcenclen.int    ; Enclave Verti Encounter near Gecko
{1479}{}{엔클레이브 경비}                 # gcenc.int       ; gecko enclave patrol guard
{1480}{}{엔클레이브 경비}                 # gcenc2.int      ; gecko enclave patrol leader
{1481}{}{금고}                          # hisafe.int      ; safe at hubologist stash
{1482}{}{경비}                         # hcdorgrd.int    ; Door Guard at Hub Stash
{1483}{}{허볼로지스트}                    # hcstldr.int     ; Leader at the Hub Stash
{1484}{}{허볼로지스트 경비}              # hcguard.int     ; generic Hub stash guard
{1485}{}{허볼로지스트 경비}              # hcguard2.int    ; generic Hub stash guard
{1486}{}{금속 문}                    # himndor.int     ; Main Door to Hubologist Stash
{1487}{}{맵 스크립트}                    # hubstash.int    ; Map script to Hubologist Stash
{1488}{}{보관함 스크립트}              # hicontnr.int    ; script to containers in Hub Stash
{1489}{}{브라민}                       # kcdunbra.int    ; Dunton's brahmin in Klamath
{1490}{}{문}                          # slvco2.int      ; door to slave holding (not the pen)
{1491}{}{입구}                          # slvco3.int      ; script to gate of big slave pen at slavers camp
{1492}{}{부족장}                  # tribec12.int    ; Chief to primitive tribe
{1493}{}{소리치는 남자}                   # ncbrkmn.int     ; Barking man in New Reno
{1494}{}{EPA 맵 스크립트}               # epa1.int        ; EPA Map Script (epax.map)
{1495}{}{EPA 메인}                      # epa2.int        ; SubLevels Map
{1496}{}{EPA 비밀 구역}              # epa3.int        ; EPA Secret Level
{1497}{}{Mr. 핸디 로봇}               # epac1.int       ; Script for depressed Mr Handy
{1498}{}{홀로그램 00000}                # epac2.int       ; Hologram 00000 script
{1499}{}{용감한 꼬마 토스터}      # epac3.int       ; Talking Toaster
{1500}{}{홀로그램 10001}                # epac4.int       ; Script for Hologram 10001
{1501}{}{홀로그램 12001}                # epac5.int       ; Script Hologram 12001
{1502}{}{홀로그램 10031}                # epac6.int       ; Script for Hologram 10031
{1503}{}{홀로그램 40011}                # epac7.int       ; Script for Hologram 40011
{1504}{}{EPA 식물}                     # epac8.int       ; Script for EPA Plants
{1505}{}{Mr. 화학!}                  # epac9.int       ; Script for crafting computer
{1506}{}{덱스}                           # epac10.int      ; Script for Diplomatic/Evil player
{1507}{}{캣 쥴스}                     # epac11.int      ; Script for combat char from the vats
{1508}{}{키츠네}                       # epac12.int      ; Script for Stealth Character
{1509}{}{전사}                       # epac13.int      ; Doctor's personal bodyguards
{1510}{}{살충제}                     # epac14.int      ; Script for bug spray
{1511}{}{박사의 포로}             # epac15.int      ; Script for captured tribals
{1512}{}{거대 개미}                     # epac16.int      ; Script for EPA ants
{1513}{}{박사}                    # epac17.int      ; Script for EPA Doctor
{1514}{}{초파리}                     # epac18.int      ; Script for mutant fruit flies
{1515}{}{생물}                      # epac19.int      ; Script for doctors crestures
{1516}{}{로봇}                         # epac20.int      ; Script for the moving robots
{1517}{}{로봇}                         # epac21.int      ; robot script
{1518}{}{EPA 전단}                   # epai1.int       ; A leaflet for the EPA
{1519}{}{음성 컴퓨터}                # epai2.int       ; Script for voice computer
{1520}{}{연구 컴퓨터}             # epai3.int       ; Script for main research computer
{1521}{}{전기 의자 컴퓨터}       # epai4.int       ; Script for Electric Chair Computer
{1522}{}{전자식 문}               # epai5.int       ; Script for Electronic doors
{1523}{}{홀로그램 생성기}            # epai6.int       ; Script for Hologram Generator
{1524}{}{보안 문}                 # epai7.int       ; Script for Security doors
{1525}{}{승강기 문}                 # epai8.int       ; Script for Elevator doors
{1526}{}{문}                          # epai9.int       ; Script for doors on ground level
{1527}{}{알 수 없는 화학물질}              # epai10.int      ; Script for Random Chemicals
{1528}{}{비옥한 토지}                # epai11.int      ; script for ground in arroyo
{1529}{}{비옥한 토지}                # epai12.int      ; fertile ground 2 script
{1530}{}{동면 컴퓨터}          # epai13.int      ; Script for Hibernation Computer
{1531}{}{조명 발전기}            # epai14.int      ; Script for Lighting Generator
{1532}{}{역장}                    # epai15.int      ; Script for forcefield to release Holograms
{1533}{}{제초제}                   # epai16.int      ; Script for Plant spray
{1534}{}{자기 코일 컴퓨터}        # epai17.int      ; Script for Magnetic coil computer
{1535}{}{역장}                    # epai18.int      ; Script for Forcedfield to warriors
{1536}{}{영사기}            # epai19.int      ; Script for projection of Hologram00000
{1537}{}{문}                          # epai20.int      ; door to chemical level
{1538}{}{컴퓨터}                      # epai21.int      ; Location Finder
{1539}{}{문}                          # epai22.int      ; Script for doors that look like elevators
{1540}{}{컴퓨터}                      # epai23.int      ; Script for computer controlling forcefields
{1541}{}{역장}                    # epai24.int      ; Script for forcefield for critters
{1542}{}{다이너마이트}                      # epai25.int      ; Script for dynamite
{1543}{}{다이너마이트 폭파장치}              # epai26.int      ; Script for dynamite trigger
{1544}{}{책상 위의 물건}                 # epai27.int      ; Script for finding paper
{1545}{}{락커}                        # epai28.int      ; Script for passcoded locker
{1546}{}{공간 스크립트}                # epas1.int       ; Elevator Spatial Script
{1547}{}{공간 스크립트}                # epas2.int       ; Gas Level Spatial Script
{1548}{}{공간 스크립트}                # epas3.int       ; Spatial script for electric chair
{1549}{}{공간 스크립트}                # epas4.int       ; Spatial script for chemicals
{1550}{}{공간 스크립트}                # epas5.int       ; Spatial script for elevator2
{1551}{}{공간 스크립트}                # epas6.int       ; Spatial script for message about magnetic field
{1552}{}{공간 스크립트}                # epas7.int       ; Spatial script on entry to the gas areas
{1553}{}{공간 스크립트}                # epas8.int       ; Spatial script for access to vents idea
{1554}{}{공기 통풍구}         # epai29.int      ; Vent to allow player to enter vent shafts of epa
{1555}{}{환기팬}                           # epai30.int      ; Left Fan Script
{1556}{}{환기팬}                           # epai31.int      ; Right Fan Script
{1557}{}{공간 스크립트}                # epas2a.int      ; Fumes near Mr. Chemmie (become harmless when fans fixed)
{1558}{}{컴퓨터 단말기}             # epai32.int      ; EPA Biology Terminal
{1559}{}{비옥한 토지}                # epai33.int      ; Ground where EPA seeds can be planted
{1560}{}{spatial}                       # epas9.int       ; Spatial script for sprouted seeds
{1561}{}{홀로그램}                    # epac22.int      ; Malfunctioning hologram
{1562}{}{spatial}                       # epas10.int      ; spatial for EPA's Air, Water, and Power Facility Level
{1563}{}{}                              # epac23.int      ; Monster in Doctor's maze
{1564}{}{홀로그램 컴퓨터}             # epai34.int      ; machine controlling hologram that gives static
{1565}{}{아이}                         # vilchild.int    ; Children at Vault Village
{1566}{}{spatial}                       # vsraispt.int    ; spatial for catching the raiders in the act at VC
{1567}{}{버티버드}                     # civerti.int     ; Flyable Vertibird
{1568}{}{컴퓨터}                      # cisactrl.int    ; Navarro Satellite control computer
{1569}{}{spatial}                       # qsvertel.int    ; spatial for vertibird elevator at enclave
{1570}{}{Mr. 핸디}                     # qcwrkbot.int    ; Worker bot (enclave verti pad)
{1571}{}{핵폭탄}                          # qinuke.int      ; Nuke at the Enclave
{1572}{}{우물}                          # viwell.int      ; VC Courtyard Well
{1573}{}{우물}                          # giwell.int      ; Gecko Well
{1574}{}{}                              # patchinf.int    ; Patch Information Script
{1575}{}{NCR 레인저}                    # scrangr.int     ; Ranger at a safe house
{1576}{}{오브젝트 이름}                   # ncrngsh1.int    ; Maps script to Ranger Safe House 1
{1577}{}{오브젝트 이름}                   # ncrngsh2.int    ; Maps script to Ranger Safe House 2
{1578}{}{오브젝트 이름}                   # ncrngsh3.int    ; Maps script to Ranger Safe House 3
{1579}{}{Map}                           # sirngmap.int    ; Ranger Safe House Map
{1580}{}{NCR 레인저}                    # scatkrng.int    ; Ranger that aids you in attack on Slaver Camp
{1581}{}{노예상인}                        # scatkslv.int    ; Slaver that aids you in attack on Ranger Safe Houses
{1582}{}{}                              # ktcavn1.int     ; creates rubble when you destroy supports
{1583}{}{}                              # ktcavn2.int     ; creates rubble when you destroy supports
{1584}{}{}                              # ktcavn3.int     ; creates rubble when you destroy supports
{1585}{}{}                              # ktcavn4.int     ; creates rubble when you destroy supports
{1586}{}{}                              # klaratcv.int    ; Rat Caves at Klamath
{1587}{}{}                              # rtcavn1.int     ; Creates a cave in if the support beam is destroyed
{1588}{}{}                              # scdmymk.int     ; Dummy script for Merk and his guards
{1589}{}{문}                          # kivicdor.int    ; Door to Vic's house in Klamath
{1590}{}{}                              # simrkstr.int    ; Script to stairs leading to Merk's basement
{1591}{}{폭력배}                          # dcg1grd2.int    ; Tyler's Friend (he's having the party)
{1592}{}{인계 철선}                     # witripwr.int    ; Trip Wire in SAD (level 2)
{1593}{}{인계 철선 공간 스크립트}             # wstripwr.int    ; Spatial for Trip Wire in SAD (level 2)
{1594}{}{매춘부}                    # dcprosti.int    ; Prostitute at Tyler's Party (Den)
{1595}{}{끈적거리는 물질}                           # esgoo.int       ; Goo in EPA
{1596}{}{Spatial}                       # wstrpwr2.int    ; Spatial that trips the wire in SAD
{1597}{}{동면실 공간 스크립트}   # eshib.int       ; Hibernation Chamber spatial
{1598}{}{}                              # nscody.int      ; Spatial script for Cody's death
{1599}{}{락커}                        # eplkr.int       ; Script controlling the lockers holding the NPC's belongings (EPA)
{1600}{}{맵 스크립트}                    # easter.int      ; RP Easter Egg Map Script
{1601}{}{모더}                        # eastereg.int    ; Script for all those who helped make the RP possible
{1602}{}{Smoking}                       # zismoke.int     ; Script used by cigs/weed
{1603}{}{Peeing}                        # peeing.int      ; Script for player peeing
{1604}{}{맵 스크립트}                    # abbasem.int     ; Abbey Basement
{1605}{}{맵 스크립트}                    # abundgr.int     ; Abbey Underground
{1606}{}{무역상}                      # tribemer.int    ; Roy the merchant
{1607}{}{무역상 경비}                # tribemg1.int    ; Warren - Roy's bodyguard
{1608}{}{무역상 경비}                # tribemg2.int     ; Second guard for Roy the Merchant
{1609}{}{상인 맵}                  # merchant.int     ; Map Script to Primitive Tribe Merchant Encounter
{1610}{}{컴퓨터}                      # epai35.int      ; EPA museum computer
{1611}{}{컴퓨터}                      # epai36.int      ; EPA petting zoo computer
{1612}{}{오토-닥}                      # epai37.int      ; EPA Character Modification Machine
{1613}{}{제이슨 수사}                 # abjason.int     ; Angry monk at Abbey
{1614}{}{토드}                          # viltodd.int     ; Little Todd - Vault Village
{1615}{}{로버트 바론}                  # vibaron.int     ; Robert Baron - Vault Village caravan provider
{1616}{}{경비}                         # vimergrd.int    ; Merchant Guard - Robert Baron
{1617}{}{상자}                         # tribei2.int     ; Crate of Stimpacks (Primitive Tribe)
{1618}{}{굶주린 인간}                # epac24.int      ; Ravenous Humans at EPA Green Level
{1619}{}{지도}                           # vilmerch.int    ; Vault Village Merchant Map
{1620}{}{역장 패널}             # epai38.int      ; force field panel (EPA level 7)
{1621}{}{환기 팬}                           # epai39.int      ; Fan to enter EPA base
{1622}{}{경비}                         # fcbtgrd.int     ; Shi Motor Boat Guard
{1623}{}{모터 보트}                    # sfmboat.int     ; Script to Motor Boat at Shi Docks
{1624}{}{경비}                         # fcbtech.int     ; Shi Sub Tech Guard
{1625}{}{고물}                          # abjunk.int      ; Abbey Junk Piles
{1626}{}{계단}                        # epai40.int      ; EPA Greenhouse stairs
{1627}{}{승강기 통로}                # epai41.int      ; EPA broken elevator shaft entrance
{1628}{}{spatial}                       # epas11.int      ; EPA elevator shaft entrance spatial
{1629}{}{승강기 통로}                # epai42.int      ; EPA elevator shaft level 1
{1630}{}{락커}                        # epai43.int      ; EPA Locker with Solar Scorcher
{1631}{}{항만 경비}                    # fcdokgrd.int    ; Shit Guard at Motor Boat
{1632}{}{기술자}                    # fcsbtec1.int    ; Sub Power Console Techie
{1633}{}{기술자}                    # fcsbtec2.int    ; Sub Target Console Techie
{1634}{}{기술자}                    # fcsbtec3.int    ; Sub Torpedo Console Techie
{1635}{}{spatial}                       # httunnel.int    ; spatial script for Broken Hills tunnels
{1636}{}{항만 노동자}                   # fcdkwrk2.int    ; Named Shi Dock Worker (gives info about sub)
{1637}{}{맵 스크립트}                    # sfsub.int       ; Shi Sub Map
{1638}{}{문}                          # fssubdr.int     ; Shi Sub Rusted Door
{1639}{}{spatial}                       # fssubint.int    ; Shi Sub Interior Greeting Spatial
{1640}{}{동력 제어반}                 # fcsubpwr.int    ; Shi Sub Power Console
{1641}{}{어뢰 제어반}               # fcsubtco.int    ; Shi Sub Torpedo Console
{1642}{}{표적 제어반}             # fcsubtar.int    ; Shi Sub Targeting Console
{1643}{}{어뢰 구역}                   # fcsubtor.int    ; Shi Sub Torpedo Bay
{1644}{}{잠수함 해치}                     # fcsubhat.int    ; Shi Sub Outer Hatch
{1645}{}{경비}                         # fcsubgrd.int    ; Shi Sub Guard
{1646}{}{버티버드}                     # ncverti.int     ; Vertibird at Salvatore Secret Transaction
{1647}{}{spatial}                       # fssubsp.int     ; Shi Sub Interior Text Spatial
{1648}{}{혈청}                         # epai44.int      ; Agility +1 serum at the EPA
{1649}{}{늙은 행상 경비}             # abguard.int     ; Retired Caravan Guard
{1650}{}{솅 박사}                     # fcdrshng.int    ; Dr. Sheng
{1651}{}{식물 생명체}                # fcplntmn.int    ; Dr. Sheng's Plant Creature
{1652}{}{솅 박사의 은신처}           # sfsheng.int     ; Dr. Sheng's hideout
{1653}{}{문}                          # fcshngdr.int    ; Door to Dr. Sheng's laboratory
{1654}{}{문}                          # fcshngd2.int    ; Door to Dr. Sheng's experiments
{1655}{}{spatial}                       # tribesp4.int    ; Spatial script upon entering the main area of Umbra Tribe
{1656}{}{수리 로봇}                  # wcrpbot2.int    ; Sierra Base, Repair Robot (generic), level 4
{1657}{}{보안 로봇}                # wcscbot2.int    ; Sierra Base, Security Robot (generic), level 4
{1658}{}{문}                          # wibaydr2.int    ; Sierra Base Repair Bay Door (level 4)